#!/usr/bin/env python3
"""Generate the shared case/fold tables used by every text worker.

Why tables instead of each language's standard library: Java, C++, Go, Python and JavaScript ship
different case tables and different Unicode versions, and C++/Go have no Unicode data at all without
a dependency. The contract therefore says "apply this file" rather than "lowercase the string", and
every implementation reads the same bytes. The files are generated from Python's unicodedata
(Unicode 15 tables as shipped with the local CPython), so they are reproducible on this machine and
reviewable as data.

Run from the repository root:  python workers/spec/generate-tables.py
"""

import json
import pathlib
import unicodedata

OUT = pathlib.Path(__file__).resolve().parent
MAX = 0x024F  # Latin-1 Supplement + Latin Extended-A + Latin Extended-B (partial)

# Letters that do not decompose under NFKD but are still Latin letters with an obvious ASCII
# spelling. Without this list, "Łódź" would never match "lodz" and Ø/ø would stay un-folded.
OVERRIDES = {
    0x00C6: "AE", 0x00E6: "ae",  # AE, ae
    0x00D0: "D", 0x00F0: "d",    # Eth
    0x00D8: "O", 0x00F8: "o",    # O with stroke
    0x00DE: "TH", 0x00FE: "th",  # Thorn
    0x00DF: "ss",                # sharp s
    0x0110: "D", 0x0111: "d",    # D with stroke
    0x0126: "H", 0x0127: "h",    # H with stroke
    0x0131: "i",                 # dotless i
    0x0130: "i",                 # capital I with dot above: its lowercase is two code points, so the
                                 # one-to-one lower table cannot carry it - but a deduplicating fold
                                 # still has to turn "İstanbul" into "istanbul"
    0x0138: "k",                 # kra
    0x0141: "L", 0x0142: "l",    # L with stroke
    0x014A: "N", 0x014B: "n",    # Eng
    0x0152: "OE", 0x0153: "oe",  # OE
    0x0166: "T", 0x0167: "t",    # T with stroke
    0x017F: "s",                 # long s
    0x0192: "f",                 # f with hook
    0x0237: "j",                 # dotless j
}


def strip_marks(ch: str) -> str:
    decomposed = unicodedata.normalize("NFKD", ch)
    return "".join(c for c in decomposed if unicodedata.category(c) != "Mn")


def build_lower() -> dict:
    table = {}
    for cp in range(0, MAX + 1):
        ch = chr(cp)
        lowered = ch.lower()
        # One code point to one code point only: U+0130 lowercases to two code points and is
        # deliberately absent, because a one-to-one table must not lie about it.
        if len(lowered) == 1 and lowered != ch:
            table[cp] = ord(lowered)
    return table


def build_fold() -> dict:
    table = {}
    for cp in range(0, MAX + 1):
        ch = chr(cp)
        folded = strip_marks(ch)
        if folded and folded != ch and folded.isascii():
            table[cp] = folded
    for cp, folded in OVERRIDES.items():
        table[cp] = folded
    # A code point must never fold to a string that is not ASCII, and never to itself.
    for cp, folded in list(table.items()):
        assert folded.isascii() and folded != chr(cp), (hex(cp), folded)
    return table


def write(name: str, table: dict, note: str) -> None:
    path = OUT / name
    payload = {
        "_note": note,
        "_source": "generated by workers/spec/generate-tables.py (Python unicodedata, Unicode 15)",
        "_domain": "U+0000-U+024F",
        "map": {str(k): v for k, v in sorted(table.items())},
    }
    path.write_text(json.dumps(payload, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"{name}: {len(table)} entries -> {path}")


write(
    "latin-lower.json",
    build_lower(),
    "Code point -> lowercase code point. Applied by text.normalize step 3 and by nothing else.",
)
write(
    "latin-fold.json",
    build_fold(),
    "Code point -> ASCII replacement string. Applied by text.normalize step 4, after lowercasing.",
)
