#!/usr/bin/env Rscript
# =============================================================================================
# workers/r/vmltext.R - the R implementation of the three text capabilities of docs/WORKERS.md:
# text.normalize (section 2), text.extract (section 3) and text.fingerprint (section 4), behind
# the JSON-Lines protocol of section 1 (one JSON object per line, UTF-8, describe/invoke/shutdown,
# ok/error envelopes, stdout carries protocol lines and nothing else, stderr carries English
# diagnostics, and stdout is flushed after every response).
#
# Base R only. No package is loaded, nothing is downloaded, and no runtime library's Unicode data
# is consulted: the case and fold tables come from workers/spec/*.json through
# workers/r/tables.generated.R, generated by workers/r/build.mjs. tolower() and toupper() are
# deliberately never called - four languages applying their own case tables is exactly how four
# implementations of this contract end up disagreeing.
#
# Four decisions worth stating before the code, because each one is a place where the obvious R
# answer is wrong:
#
#  1. THIS FILE IS PURE ASCII, AND SO IS THE GENERATED TABLE FILE. R parses a source file using the
#     session's encoding, and a source file that is UTF-8 on one machine is GBK on the next. Every
#     literal here is ASCII, and every non-ASCII code point that matters (the case and fold tables,
#     the mapping targets, the entity values, the expected selfcheck results) is written as a
#     number.
#
#  2. TEXT IS AN INTEGER VECTOR OF CODE POINTS, NEVER AN R STRING. R strings carry an encoding mark
#     and are transcoded to the session's native encoding on output, which on a non-UTF-8 Windows
#     machine would corrupt exactly the CJK text the contract insists must survive unchanged. So
#     the worker decodes stdin bytes to code points itself (hand-rolled UTF-8 decoder, so an
#     invalid sequence cannot make R abort), works on integer vectors, and encodes the answer back
#     to UTF-8 bytes itself. nchar(), substr(), strsplit(), regexpr() and the tolower() family are
#     never called: they are all locale- and encoding-sensitive.
#
#  3. 64-BIT ARITHMETIC WITHOUT 64-BIT INTEGERS. R's integer is 32-bit and R's double is exact only
#     up to 2^53, so (h * 1099511628211) %% 2^64 in doubles is wrong - the product needs 105 bits.
#     The accumulator is therefore kept as two 32-bit words (hi, lo) held in doubles, and each
#     multiplication splits the prime into 16-bit halves, P = 16777216 * 2^16 + 435, so that the
#     largest intermediate value is about 1.1e12 - three orders of magnitude below 2^53, and every
#     step is exact. See vml_fnv1a64_cps() below and the README.
#
#  4. LINE ENDINGS ON WINDOWS. The contract says LF. R's stdout is a text-mode stream, and on
#     Windows the C runtime rewrites every LF written to it as CR LF; base R exposes no _setmode,
#     "writeBin" refuses a terminal connection ("can only write to a binary connection"),
#     file("stdout", "wb") is not special-cased on R 4.6 and creates a file literally named
#     "stdout", and calling _setmode() on ucrtbase.dll through .C() does not clear the translation
#     flag of the already-initialised FILE stream. So this worker's lines end in CR LF on Windows.
#     The JSON content is byte-identical and JSON.parse() treats the CR as whitespace, so the
#     conformance harness is unaffected; it is reported in the README rather than papered over.
#
# Usage (the host appends the capability; see docs/WORKERS.md section 1.1):
#   Rscript workers/r/vmltext.R --capability text.normalize
#   Rscript workers/r/vmltext.R --capability text.extract
#   Rscript workers/r/vmltext.R --capability text.fingerprint
#   Rscript workers/r/vmltext.R --selfcheck
# =============================================================================================

# ---------------------------------------------------------------------------------------------
# 0. Small ASCII helpers. A() turns an ASCII literal into a code point vector; nothing here ever
#    depends on the locale, and nothing here ever builds an R string with an encoding mark.
# ---------------------------------------------------------------------------------------------

A <- function(s) as.integer(charToRaw(s))

VML_HEX_DIGITS <- c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f")

VML_LT <- 60L
VML_GT <- 62L
VML_AMP <- 38L
VML_SLASH <- 47L
VML_BANG <- 33L
VML_HASH <- 35L
VML_SEMI <- 59L
VML_EQUALS <- 61L
VML_DQUOTE <- 34L
VML_SQUOTE <- 39L
VML_SPACE <- 32L
VML_COLON <- 58L
VML_DASH <- 45L

VML_CAPABILITIES <- c("text.normalize", "text.extract", "text.fingerprint")

vml_diag <- function(...) {
  cat(..., "\n", sep = "", file = stderr())
  flush(stderr())
  invisible(NULL)
}

vml_fatal <- function(...) {
  vml_diag(...)
  quit(save = "no", status = 1L, runLast = FALSE)
}

# The code-point slice helper. R's x[a:b] counts DOWN when a > b, which turns "empty slice" into
# "two characters in the wrong order", and x[beyond the end] pads with NA, which turns a scan into a
# "missing value where TRUE/FALSE needed" crash. Both are silent hazards in a hand-written scanner,
# so both are closed here, once.
vml_slice <- function(x, a, b) {
  if (b < a) return(x[0L])
  n <- length(x)
  if (a > n) return(x[0L])
  if (b > n) b <- n
  x[a:b]
}

vml_is_ascii_letter <- function(cp) (cp >= 65L & cp <= 90L) | (cp >= 97L & cp <= 122L)
vml_is_ascii_digit <- function(cp) cp >= 48L & cp <= 57L
vml_is_ascii_alnum <- function(cp) vml_is_ascii_letter(cp) | vml_is_ascii_digit(cp)
# JavaScript's \w: ASCII letters, digits and underscore. Used for the word-boundary test.
vml_is_word_cp <- function(cp) vml_is_ascii_alnum(cp) | cp == 95L
vml_is_hex_digit <- function(cp) vml_is_ascii_digit(cp) | (cp >= 65L & cp <= 70L) | (cp >= 97L & cp <= 102L)
vml_hex_value <- function(cp) if (cp <= 57L) cp - 48L else vml_ascii_lower(cp) - 87L

vml_ascii_lower <- function(cps) {
  if (is.raw(cps)) cps <- as.integer(cps)
  up <- cps >= 65L & cps <= 90L
  if (any(up)) cps[up] <- cps[up] + 32L
  cps
}

# JavaScript's \s (not R's [[:space:]], which is locale-dependent and a different set).
VML_JS_SPACE_CPS <- c(9L, 10L, 11L, 12L, 13L, 32L, 160L, 5760L, 0x2000L:0x200AL, 0x2028L, 0x2029L,
                      0x202FL, 0x205FL, 0x3000L, 0xFEFFL)
vml_is_js_space_cp <- function(cp) cp %in% VML_JS_SPACE_CPS

# ---------------------------------------------------------------------------------------------
# 1. UTF-8 codec, hand-rolled on purpose. Decoding never raises: an invalid byte becomes U+FFFD,
#    as a permissive decoder would, instead of aborting the worker.
# ---------------------------------------------------------------------------------------------

vml_utf8_decode <- function(bytes) {
  n <- length(bytes)
  if (n == 0L) return(integer(0))
  b <- as.integer(bytes)
  if (all(b < 128L)) return(b)
  out <- vector("list", 0L)
  k <- 0L
  i <- 1L
  while (i <= n) {
    b1 <- b[i]
    if (b1 < 128L) {
      # copy the whole ASCII run at once
      j <- i
      while (j <= n && b[j] < 128L) j <- j + 1L
      k <- k + 1L
      out[[k]] <- b[i:(j - 1L)]
      i <- j
      next
    }
    need <- if (b1 >= 240L) 4L else if (b1 >= 224L) 3L else if (b1 >= 192L) 2L else 0L
    ok <- need > 0L && (i + need - 1L) <= n
    if (ok) {
      cont <- b[(i + 1L):(i + need - 1L)]
      ok <- all(cont >= 128L & cont <= 191L)
    }
    if (ok && need == 2L) ok <- b1 >= 194L
    if (ok && need == 3L) ok <- !(b1 == 224L && b[i + 1L] < 160L)
    if (ok && need == 4L) ok <- b1 <= 244L && !(b1 == 240L && b[i + 1L] < 144L) && !(b1 == 244L && b[i + 1L] > 143L)
    if (!ok) {
      k <- k + 1L
      out[[k]] <- 0xFFFDL
      i <- i + 1L
      next
    }
    # switch() counts its alternatives from 1, so the index is need - 1: 2-byte, 3-byte, 4-byte.
    cp <- switch(need - 1L,
      (b1 - 192L) * 64L + (b[i + 1L] - 128L),
      (b1 - 224L) * 4096L + (b[i + 1L] - 128L) * 64L + (b[i + 2L] - 128L),
      (b1 - 240L) * 262144L + (b[i + 1L] - 128L) * 4096L + (b[i + 2L] - 128L) * 64L + (b[i + 3L] - 128L)
    )
    k <- k + 1L
    out[[k]] <- as.integer(cp)
    i <- i + need
  }
  unlist(out[seq_len(k)], use.names = FALSE)
}

# Lone surrogates and out-of-range values become U+FFFD, which is what Node's UTF-8 encoder does
# with them; the contract's input is well-formed, so this only keeps a malformed byte out of the
# output instead of producing invalid UTF-8.
vml_utf8_encode <- function(cps) {
  n <- length(cps)
  if (n == 0L) return(raw(0))
  cp <- as.integer(cps)
  bad <- is.na(cp) | cp < 0L | cp > 0x10FFFFL | (cp >= 0xD800L & cp <= 0xDFFFL)
  if (any(bad)) cp[bad] <- 0xFFFDL
  len <- ifelse(cp < 0x80L, 1L, ifelse(cp < 0x800L, 2L, ifelse(cp < 0x10000L, 3L, 4L)))
  out <- integer(sum(len))
  pos <- cumsum(len) - len + 1L
  s1 <- len == 1L
  if (any(s1)) out[pos[s1]] <- cp[s1]
  s2 <- len == 2L
  if (any(s2)) {
    out[pos[s2]] <- 0xC0L + cp[s2] %/% 64L
    out[pos[s2] + 1L] <- 0x80L + cp[s2] %% 64L
  }
  s3 <- len == 3L
  if (any(s3)) {
    out[pos[s3]] <- 0xE0L + cp[s3] %/% 4096L
    out[pos[s3] + 1L] <- 0x80L + (cp[s3] %/% 64L) %% 64L
    out[pos[s3] + 2L] <- 0x80L + cp[s3] %% 64L
  }
  s4 <- len == 4L
  if (any(s4)) {
    out[pos[s4]] <- 0xF0L + cp[s4] %/% 262144L
    out[pos[s4] + 1L] <- 0x80L + (cp[s4] %/% 4096L) %% 64L
    out[pos[s4] + 2L] <- 0x80L + (cp[s4] %/% 64L) %% 64L
    out[pos[s4] + 3L] <- 0x80L + cp[s4] %% 64L
  }
  as.raw(out)
}

# A code point vector as an R string holding exactly those UTF-8 bytes. rawToChar() leaves the
# encoding mark unset ("unknown" = native), and R writes an unmarked string byte for byte without
# transcoding, which is precisely what a UTF-8 transport needs on a GBK-locale machine.
vml_to_native_bytes_string <- function(cps) rawToChar(vml_utf8_encode(cps))

# Readable, ASCII-only rendering for diagnostics and the selfcheck report: a console in a non-UTF-8
# code page cannot be trusted to show CJK correctly, and a selfcheck that cannot be read is useless.
vml_repr <- function(cps) {
  if (length(cps) == 0L) return("\"\"")
  parts <- character(length(cps))
  for (i in seq_along(cps)) {
    cp <- cps[i]
    parts[i] <- if (cp >= 32L && cp < 127L && cp != 34L && cp != 92L) {
      rawToChar(as.raw(as.integer(cp)))
    } else if (cp == 34L) {
      "\\\""
    } else if (cp == 92L) {
      "\\\\"
    } else if (cp < 0x10000L) {
      sprintf("\\u%04x", as.integer(cp))
    } else {
      sprintf("\\U%08x", as.integer(cp))
    }
  }
  paste0("\"", paste(parts, collapse = ""), "\"")
}

# ---------------------------------------------------------------------------------------------
# 2. The shared tables. VML_LOWER and VML_FOLD are sourced from tables.generated.R, which
#    workers/r/build.mjs emits from workers/spec/latin-lower.json and latin-fold.json. Nothing in
#    this file falls back to an R case table: if the generated file is missing, the worker refuses
#    to run, because guessing is how implementations silently disagree.
# ---------------------------------------------------------------------------------------------

vml_script_path <- function() {
  a <- commandArgs(trailingOnly = FALSE)
  f <- grep("^--file=", a, value = TRUE)
  if (length(f) == 0L) return(NULL)
  sub("^--file=", "", f[1L])
}

vml_load_tables <- function() {
  p <- vml_script_path()
  path <- if (is.null(p)) "tables.generated.R" else file.path(dirname(p), "tables.generated.R")
  if (!file.exists(path)) {
    vml_fatal("error: ", path, " is missing; build it with: node workers/r/build.mjs")
  }
  source(path, local = FALSE)
  if (!exists("VML_LOWER", inherits = TRUE) || !exists("VML_FOLD", inherits = TRUE)) {
    vml_fatal("error: ", path, " did not define VML_LOWER and VML_FOLD")
  }
  if (length(VML_LOWER) < 592L || length(VML_FOLD) < 592L) {
    vml_fatal("error: ", path, " is not the table shape this worker expects (length >= 592)")
  }
  invisible(TRUE)
}

# ---------------------------------------------------------------------------------------------
# 3. JSON: a hand-rolled reader and writer. Base R has neither, and the protocol only needs
#    objects, arrays, strings with the full escape set (including \uXXXX with surrogate pairs),
#    numbers echoed verbatim, booleans and null.
#
#    A parsed value is a list(t = <type>, v = <value>):
#      null  -> v NULL            bool -> v TRUE/FALSE        num -> v code points of the literal
#      str   -> v code point vector                            arr -> v list of values
#      obj   -> v named list of values (names are ASCII)
# ---------------------------------------------------------------------------------------------

vml_jnull <- function() list(t = "null", v = NULL)
vml_jbool <- function(b) list(t = "bool", v = isTRUE(b))
vml_jnum <- function(n) list(t = "num", v = A(vml_format_int(n)))
vml_jstr <- function(cps) list(t = "str", v = as.integer(cps))
vml_jarr <- function(items) list(t = "arr", v = items)
vml_jobj <- function(fields) list(t = "obj", v = fields)

vml_format_int <- function(x) {
  x <- as.numeric(x)
  if (!is.finite(x) || x < 0) return("0")
  if (x == 0) return("0")
  digs <- character(0)
  while (x > 0) {
    digs <- c(digs, VML_HEX_DIGITS[[as.integer(x %% 10) + 1L]])
    x <- x %/% 10
  }
  paste(rev(digs), collapse = "")
}

vml_json_reader <- function(cps) {
  st <- new.env(parent = emptyenv())
  st$cps <- cps
  st$n <- length(cps)
  st$i <- 1L

  st$peek <- function() if (st$i <= st$n) st$cps[st$i] else NA_integer_
  st$skip_ws <- function() {
    while (st$i <= st$n) {
      cp <- st$cps[st$i]
      if (cp == 32L || cp == 9L || cp == 10L || cp == 13L) st$i <- st$i + 1L else break
    }
  }
  st$fail <- function(what) stop(structure(class = c("vml_json_error", "error", "condition"),
                                           list(message = what, call = NULL)))
  st$parse_value <- function() {
    st$skip_ws()
    if (st$i > st$n) st$fail("unexpected end of input")
    cp <- st$cps[st$i]
    if (cp == 123L) return(st$parse_object())
    if (cp == 91L) return(st$parse_array())
    if (cp == 34L) return(vml_jstr(st$parse_string()))
    if (cp == 116L) { st$expect_word("true"); return(vml_jbool(TRUE)) }
    if (cp == 102L) { st$expect_word("false"); return(vml_jbool(FALSE)) }
    if (cp == 110L) { st$expect_word("null"); return(vml_jnull()) }
    if (cp == 45L || (cp >= 48L && cp <= 57L)) return(st$parse_number())
    st$fail("unexpected character in JSON")
  }
  st$expect_word <- function(w) {
    need <- A(w)
    if (st$i + length(need) - 1L > st$n) st$fail("unexpected end of input")
    if (!all(st$cps[st$i:(st$i + length(need) - 1L)] == need)) st$fail(paste0("expected ", w))
    st$i <- st$i + length(need)
    invisible(NULL)
  }
  st$parse_number <- function() {
    start <- st$i
    while (st$i <= st$n) {
      cp <- st$cps[st$i]
      if ((cp >= 48L && cp <= 57L) || cp == 45L || cp == 43L || cp == 46L || cp == 101L || cp == 69L) {
        st$i <- st$i + 1L
      } else break
    }
    if (st$i == start) st$fail("malformed number")
    list(t = "num", v = st$cps[start:(st$i - 1L)])
  }
  st$parse_string <- function() {
    st$i <- st$i + 1L # opening quote
    out <- vector("list", 0L)
    k <- 0L
    repeat {
      if (st$i > st$n) st$fail("unterminated string")
      cp <- st$cps[st$i]
      if (cp == 34L) { st$i <- st$i + 1L; break }
      if (cp == 92L) {
        st$i <- st$i + 1L
        if (st$i > st$n) st$fail("unterminated escape")
        e <- st$cps[st$i]
        st$i <- st$i + 1L
        if (e == 117L) { # \uXXXX, with surrogate pairs joined into one code point
          if (st$i + 3L > st$n) st$fail("truncated \\u escape")
          hx <- st$cps[st$i:(st$i + 3L)]
          if (!all(vml_is_hex_digit(hx))) st$fail("malformed \\u escape")
          st$i <- st$i + 4L
          v <- 0L
          for (d in hx) v <- v * 16L + vml_hex_value(d)
          if (v >= 0xD800L && v <= 0xDBFFL && st$i + 5L <= st$n &&
              st$cps[st$i] == 92L && st$cps[st$i + 1L] == 117L &&
              all(vml_is_hex_digit(st$cps[(st$i + 2L):(st$i + 5L)]))) {
            lo <- 0L
            for (d in st$cps[(st$i + 2L):(st$i + 5L)]) lo <- lo * 16L + vml_hex_value(d)
            if (lo >= 0xDC00L && lo <= 0xDFFFL) {
              v <- 0x10000L + (v - 0xD800L) * 0x400L + (lo - 0xDC00L)
              st$i <- st$i + 6L
            }
          }
          k <- k + 1L
          out[[k]] <- as.integer(v)
          next
        }
        simple <- switch(as.character(e),
                         "34" = 34L, "92" = 92L, "47" = 47L, "98" = 8L, "102" = 12L,
                         "110" = 10L, "114" = 13L, "116" = 9L, NA_integer_)
        if (is.na(simple)) st$fail("unknown string escape")
        k <- k + 1L
        out[[k]] <- simple
        next
      }
      k <- k + 1L
      out[[k]] <- as.integer(cp)
      st$i <- st$i + 1L
    }
    if (k == 0L) integer(0) else unlist(out[seq_len(k)], use.names = FALSE)
  }
  st$parse_array <- function() {
    st$i <- st$i + 1L
    st$skip_ws()
    items <- list()
    if (st$peek() == 93L) { st$i <- st$i + 1L; return(vml_jarr(items)) }
    repeat {
      items[[length(items) + 1L]] <- st$parse_value()
      st$skip_ws()
      cp <- st$peek()
      if (is.na(cp)) st$fail("unterminated array")
      st$i <- st$i + 1L
      if (cp == 93L) break
      if (cp != 44L) st$fail("expected , or ] in array")
    }
    vml_jarr(items)
  }
  st$parse_object <- function() {
    st$i <- st$i + 1L
    st$skip_ws()
    keys <- character(0)
    vals <- list()
    if (st$peek() == 125L) { st$i <- st$i + 1L; return(vml_jobj(list())) }
    repeat {
      st$skip_ws()
      if (st$peek() != 34L) st$fail("expected a string key")
      kcps <- st$parse_string()
      key <- if (length(kcps) == 0L) "" else rawToChar(as.raw(as.integer(kcps)))
      st$skip_ws()
      if (st$peek() != 58L) st$fail("expected : in object")
      st$i <- st$i + 1L
      val <- st$parse_value()
      keys <- c(keys, key)
      vals[[length(vals) + 1L]] <- val
      st$skip_ws()
      cp <- st$peek()
      if (is.na(cp)) st$fail("unterminated object")
      st$i <- st$i + 1L
      if (cp == 125L) break
      if (cp != 44L) st$fail("expected , or } in object")
    }
    names(vals) <- keys
    vml_jobj(vals)
  }

  st$skip_ws()
  value <- st$parse_value()
  st$skip_ws()
  if (st$i <= st$n) st$fail("trailing characters after the JSON value")
  value
}

vml_json_string_cps <- function(cps) {
  out <- c(VML_DQUOTE)
  for (cp in cps) {
    cp <- as.integer(cp)
    if (cp == 34L) out <- c(out, 92L, 34L)
    else if (cp == 92L) out <- c(out, 92L, 92L)
    else if (cp == 8L) out <- c(out, 92L, 98L)
    else if (cp == 9L) out <- c(out, 92L, 116L)
    else if (cp == 10L) out <- c(out, 92L, 110L)
    else if (cp == 12L) out <- c(out, 92L, 102L)
    else if (cp == 13L) out <- c(out, 92L, 114L)
    else if (cp < 32L || (cp >= 0xD800L && cp <= 0xDFFFL)) {
      out <- c(out, A(sprintf("\\u%04x", cp)))
    } else out <- c(out, cp)
  }
  c(out, VML_DQUOTE)
}

vml_json_encode <- function(node) {
  switch(node$t,
    "null" = A("null"),
    "bool" = if (isTRUE(node$v)) A("true") else A("false"),
    "num" = node$v,
    "str" = vml_json_string_cps(node$v),
    "arr" = {
      parts <- lapply(node$v, vml_json_encode)
      out <- c(A("["))
      for (i in seq_along(parts)) {
        if (i > 1L) out <- c(out, A(","))
        out <- c(out, parts[[i]])
      }
      c(out, A("]"))
    },
    "obj" = {
      keys <- names(node$v)
      out <- c(A("{"))
      for (i in seq_along(node$v)) {
        if (i > 1L) out <- c(out, A(","))
        out <- c(out, vml_json_string_cps(A(keys[[i]])), A(":"), vml_json_encode(node$v[[i]]))
      }
      c(out, A("}"))
    },
    stop("unsupported JSON node")
  )
}

vml_obj_get <- function(node, key) {
  if (is.null(node) || !identical(node$t, "obj")) return(NULL)
  idx <- match(key, names(node$v))
  if (is.na(idx)) return(NULL)
  node$v[[idx]]
}

vml_as_string <- function(node) {
  if (is.null(node) || !identical(node$t, "str")) return(NULL)
  node$v
}

# ---------------------------------------------------------------------------------------------
# 4. text.normalize (docs/WORKERS.md section 2)
# ---------------------------------------------------------------------------------------------

VML_DELETE_RANGES <- list(
  c(0x0000L, 0x0008L), c(0x000BL, 0x000CL), c(0x000EL, 0x001FL), c(0x007FL, 0x007FL),
  c(0x0300L, 0x036FL), c(0x1AB0L, 0x1AFFL), c(0x1DC0L, 0x1DFFL),
  c(0x200BL, 0x200FL), c(0x202AL, 0x202EL), c(0x2060L, 0x2064L),
  c(0x20D0L, 0x20FFL), c(0xFE20L, 0xFE2FL), c(0xFEFFL, 0xFEFFL)
)

VML_SPACE_LIKE <- c(0x00A0L, 0x2000L:0x200AL, 0x2028L, 0x2029L, 0x202FL, 0x205FL, 0x3000L)
VML_SINGLE_QUOTES <- c(0x2018L, 0x2019L, 0x201BL, 0x2032L)
VML_DOUBLE_QUOTES <- c(0x201CL, 0x201DL, 0x201FL, 0x2033L)
VML_DASHES <- c(0x2010L:0x2015L, 0x2212L)

vml_is_deleted_cp <- function(cp) {
  for (r in VML_DELETE_RANGES) if (cp >= r[1L] && cp <= r[2L]) return(TRUE)
  FALSE
}

vml_map_one <- function(cp) {
  if (cp %in% VML_SPACE_LIKE) return(VML_SPACE)
  if (cp >= 0xFF01L && cp <= 0xFF5EL) return(as.integer(cp - 0xFEE0L))
  if (cp %in% VML_SINGLE_QUOTES) return(VML_SQUOTE)
  if (cp %in% VML_DOUBLE_QUOTES) return(VML_DQUOTE)
  if (cp %in% VML_DASHES) return(VML_DASH)
  if (cp == 0x2026L) return(A("..."))
  if (cp == 0x3001L) return(44L)
  if (cp == 0x3002L) return(46L)
  as.integer(cp)
}

vml_map_mask <- function(cps) {
  (cps %in% VML_SPACE_LIKE) |
    (cps >= 0xFF01L & cps <= 0xFF5EL) |
    (cps %in% VML_SINGLE_QUOTES) | (cps %in% VML_DOUBLE_QUOTES) | (cps %in% VML_DASHES) |
    (cps == 0x2026L) | (cps == 0x3001L) | (cps == 0x3002L)
}

# Replace the positions in idx with the corresponding (possibly multi-code-point) replacements.
vml_expand_at <- function(x, idx, reps) {
  if (length(idx) == 0L) return(x)
  n <- length(x)
  out <- vector("list", 0L)
  k <- 0L
  prev <- 1L
  for (t in seq_along(idx)) {
    p <- idx[t]
    if (p > prev) { k <- k + 1L; out[[k]] <- x[prev:(p - 1L)] }
    k <- k + 1L
    out[[k]] <- reps[[t]]
    prev <- p + 1L
  }
  if (prev <= n) { k <- k + 1L; out[[k]] <- x[prev:n] }
  unlist(out[seq_len(k)], use.names = FALSE)
}

vml_normalize_cps <- function(cps) {
  n <- length(cps)
  if (n == 0L) return(integer(0))

  # 1. delete
  keep <- !vapply(cps, vml_is_deleted_cp, logical(1))
  cps <- cps[keep]
  n <- length(cps)
  if (n == 0L) return(integer(0))

  # 2. map, one code point to one (or three, for U+2026)
  hit <- which(vml_map_mask(cps))
  if (length(hit) > 0L) cps <- vml_expand_at(cps, hit, lapply(cps[hit], vml_map_one))
  n <- length(cps)
  if (n == 0L) return(integer(0))

  # 3. lowercase, strictly from workers/spec/latin-lower.json
  sel <- which(cps <= 591L)
  if (length(sel) > 0L) {
    vals <- VML_LOWER[cps[sel] + 1L]
    ok <- vals != 0L
    if (any(ok)) cps[sel[ok]] <- vals[ok]
  }

  # 4. fold, strictly from workers/spec/latin-fold.json, applied to the result of step 3
  sel <- which(cps <= 591L)
  if (length(sel) > 0L) {
    reps <- VML_FOLD[cps[sel] + 1L]
    has <- lengths(reps) > 0L
    if (any(has)) cps <- vml_expand_at(cps, sel[has], reps[has])
  }
  n <- length(cps)
  if (n == 0L) return(integer(0))

  # 5. collapse runs of space, tab, LF and CR into one space
  ws <- cps == 32L | cps == 9L | cps == 10L | cps == 13L
  if (any(ws)) {
    drop <- ws
    drop[1L] <- FALSE
    if (n > 1L) drop[2:n] <- ws[2:n] & ws[1:(n - 1L)]
    cps[ws] <- 32L
    cps <- cps[!drop]
  }

  # 6. trim
  n <- length(cps)
  if (n > 0L && cps[1L] == 32L) cps <- cps[-1L]
  n <- length(cps)
  if (n > 0L && cps[n] == 32L) cps <- cps[-n]
  cps
}

# ---------------------------------------------------------------------------------------------
# 5. text.extract (docs/WORKERS.md section 3)
# ---------------------------------------------------------------------------------------------

vml_find_seq <- function(hay, needle, from = 1L) {
  m <- length(needle)
  if (m == 0L) return(NA_integer_)
  n <- length(hay)
  if (from < 1L) from <- 1L
  if (from + m - 1L > n) return(NA_integer_)
  cand <- which(hay[from:n] == needle[1L]) + from - 1L
  for (p in cand) {
    if (p + m - 1L > n) break
    if (all(hay[p:(p + m - 1L)] == needle)) return(as.integer(p))
  }
  NA_integer_
}

vml_find_cp <- function(hay, cp, from = 1L) {
  n <- length(hay)
  if (from < 1L) from <- 1L
  if (from > n) return(NA_integer_)
  w <- which(hay[from:n] == cp)
  if (length(w) == 0L) return(NA_integer_)
  as.integer(from + w[1L] - 1L)
}

vml_apply_removals <- function(src, intervals) {
  if (length(intervals) == 0L) return(src)
  keep <- rep(TRUE, length(src))
  for (iv in intervals) keep[iv[1L]:iv[2L]] <- FALSE
  src[keep]
}

# Replace each interval with its replacement text. Used by the CDATA hider, which does not delete
# the section but hides its body behind a sentinel.
vml_splice <- function(src, intervals) {
  if (length(intervals) == 0L) return(src)
  n <- length(src)
  out <- vector("list", 0L)
  k <- 0L
  prev <- 1L
  for (iv in intervals) {
    if (iv$start > prev) { k <- k + 1L; out[[k]] <- src[prev:(iv$start - 1L)] }
    if (length(iv$repl) > 0L) { k <- k + 1L; out[[k]] <- as.integer(iv$repl) }
    prev <- iv$end + 1L
  }
  if (prev <= n) { k <- k + 1L; out[[k]] <- src[prev:n] }
  if (k == 0L) return(src[0L])
  unlist(out[seq_len(k)], use.names = FALSE)
}

VML_REMOVED_ELEMENTS <- c("script", "style", "noscript", "template", "svg", "iframe")

vml_remove_one_element <- function(src, tag) {
  n <- length(src)
  if (n == 0L) return(src)
  tag_low <- vml_ascii_lower(A(tag))
  hay <- vml_ascii_lower(src)
  open_needle <- c(VML_LT, tag_low)
  close_needle <- c(VML_LT, VML_SLASH, tag_low)
  intervals <- list()
  k <- 0L
  scan <- 1L
  repeat {
    if (scan > n) break
    p <- vml_find_seq(hay, open_needle, scan)
    if (is.na(p)) break
    after <- p + length(open_needle)
    # \\b after the element name: the next character must not be a word character
    if (after <= n && vml_is_word_cp(src[after])) { scan <- p + 1L; next }
    # the open tag runs to the first '>' (the contract's regex-style pre-pass, like the reference)
    gt <- vml_find_cp(src, VML_GT, after)
    if (is.na(gt)) { scan <- p + 1L; next }
    end <- NA_integer_
    cscan <- gt + 1L
    repeat {
      q <- vml_find_seq(hay, close_needle, cscan)
      if (is.na(q)) break
      r <- q + length(close_needle)
      while (r <= n && vml_is_js_space_cp(src[r])) r <- r + 1L
      if (r <= n && src[r] == VML_GT) { end <- r; break }
      cscan <- q + 1L
    }
    if (is.na(end)) {
      # a removed element with no closing tag runs to the end of the input
      k <- k + 1L
      intervals[[k]] <- c(p, n)
      break
    }
    k <- k + 1L
    intervals[[k]] <- c(p, end)
    scan <- end + 1L
  }
  vml_apply_removals(src, intervals)
}

vml_remove_elements <- function(src) {
  for (tag in VML_REMOVED_ELEMENTS) src <- vml_remove_one_element(src, tag)
  src
}

# <![CDATA[ ... ]]> keeps its inner text - as character data, so what is inside it is literal text
# and is NOT parsed as markup afterwards. The body is therefore hidden behind a sentinel built from
# private-use code points (they cannot occur in a feed by accident) and put back at the very end,
# after every rule that could mistake it for markup has run. An unclosed section - no ]]> - keeps
# everything to the end of the input, the same principle as a removed element with no closing tag.
VML_CDATA_OPEN <- c(60L, 33L, 91L, 67L, 68L, 65L, 84L, 65L, 91L) # "<![CDATA["
VML_CDATA_CLOSE <- c(93L, 93L, 62L)                              # "]]>"
VML_SENTINEL_START <- 0xE000L
VML_SENTINEL_END <- 0xE001L

vml_cdata_hide <- function(src) {
  n <- length(src)
  bodies <- list()
  nb <- 0L
  intervals <- list()
  ki <- 0L
  scan <- 1L
  repeat {
    if (scan > n) break
    p <- vml_find_seq(src, VML_CDATA_OPEN, scan)
    if (is.na(p)) break
    q <- vml_find_seq(src, VML_CDATA_CLOSE, p + length(VML_CDATA_OPEN))
    inner_end <- if (is.na(q)) n else q - 1L
    next_pos <- if (is.na(q)) n + 1L else q + length(VML_CDATA_CLOSE)
    nb <- nb + 1L
    bodies[[nb]] <- vml_slice(src, p + length(VML_CDATA_OPEN), inner_end)
    ki <- ki + 1L
    intervals[[ki]] <- list(start = p, end = next_pos - 1L,
                            repl = c(VML_SENTINEL_START, A(vml_format_int(nb - 1L)), VML_SENTINEL_END))
    scan <- next_pos
  }
  list(src = vml_splice(src, intervals), bodies = bodies)
}

vml_cdata_restore <- function(cps, bodies) {
  if (length(bodies) == 0L || length(cps) == 0L) return(cps)
  n <- length(cps)
  intervals <- list()
  ki <- 0L
  scan <- 1L
  repeat {
    if (scan > n) break
    p <- vml_find_cp(cps, VML_SENTINEL_START, scan)
    if (is.na(p)) break
    k <- p + 1L
    while (k <= n && cps[k] >= 48L && cps[k] <= 57L) k <- k + 1L
    if (k > p + 1L && k <= n && cps[k] == VML_SENTINEL_END) {
      idx <- 0
      for (d in cps[(p + 1L):(k - 1L)]) idx <- idx * 10 + (d - 48L)
      repl <- if (idx + 1L <= length(bodies)) bodies[[idx + 1L]] else integer(0)
      ki <- ki + 1L
      intervals[[ki]] <- list(start = p, end = k, repl = repl)
      scan <- k + 1L
    } else {
      scan <- p + 1L
    }
  }
  vml_splice(cps, intervals)
}

# <!-- ... --> goes. An unterminated comment runs to the end of the input.
vml_comment_pass <- function(src) {
  open_needle <- A("<!--")
  close_needle <- A("-->")
  intervals <- list()
  k <- 0L
  scan <- 1L
  repeat {
    p <- vml_find_seq(src, open_needle, scan)
    if (is.na(p)) break
    q <- vml_find_seq(src, close_needle, p + length(open_needle))
    if (is.na(q)) {
      k <- k + 1L
      intervals[[k]] <- c(p, length(src))
      break
    }
    k <- k + 1L
    intervals[[k]] <- c(p, q + length(close_needle) - 1L)
    scan <- q + length(close_needle)
  }
  vml_apply_removals(src, intervals)
}

# <!DOCTYPE ...> goes, case-insensitively; without its '>' there is no declaration to remove.
vml_doctype_pass <- function(src) {
  open_needle <- A("<!doctype")
  hay <- vml_ascii_lower(src)
  intervals <- list()
  k <- 0L
  scan <- 1L
  repeat {
    if (scan > length(src)) break
    p <- vml_find_seq(hay, open_needle, scan)
    if (is.na(p)) break
    gt <- vml_find_cp(src, VML_GT, p + length(open_needle))
    if (is.na(gt)) { scan <- p + 1L; next }
    k <- k + 1L
    intervals[[k]] <- c(p, gt)
    scan <- gt + 1L
  }
  vml_apply_removals(src, intervals)
}

VML_NEWLINE_TAGS <- c("br", "p", "div", "li", "ul", "ol", "tr", "th", "td", "h1", "h2", "h3", "h4",
                      "h5", "h6", "section", "article", "header", "footer", "aside", "nav",
                      "blockquote", "pre", "table", "hr", "dd", "dt", "figure", "figcaption",
                      "main", "form")

VML_ENTITIES <- list(
  amp = 38L, lt = 60L, gt = 62L, quot = 34L, apos = 39L, nbsp = 0xA0L,
  mdash = 0x2014L, ndash = 0x2013L, hellip = 0x2026L, laquo = 0xABL, raquo = 0xBBL,
  copy = 0xA9L, reg = 0xAEL, trade = 0x2122L, times = 0xD7L, middot = 0xB7L
)

# Named references decode to their own character, never to the ASCII the normalizer would later
# produce: &mdash; is U+2014 here, and turning it into "-" is the normalizer's job, in another
# capability, on another day.
vml_decode_entity <- function(src, amp_index) {
  n <- length(src)
  p0 <- amp_index - 1L
  semi0 <- NA_integer_
  if (amp_index + 1L <= n) {
    w <- which(src[(amp_index + 1L):n] == VML_SEMI)
    if (length(w) > 0L) semi0 <- p0 + w[1L]
  }
  limit0 <- if (!is.na(semi0) && semi0 + 1L < p0 + 12L) semi0 + 1L else p0 + 12L
  win <- vml_slice(src, p0 + 2L, limit0)
  m <- length(win)
  if (m == 0L) return(NULL)

  body_len <- 0L
  numeric_ref <- FALSE
  hex_ref <- FALSE
  if (m >= 2L && win[1L] == VML_HASH && vml_is_ascii_digit(win[2L])) {
    k <- 2L
    while (k <= m && (k - 2L) < 7L && vml_is_ascii_digit(win[k])) k <- k + 1L
    body_len <- k - 1L
    numeric_ref <- TRUE
  } else if (m >= 3L && win[1L] == VML_HASH && (win[2L] == 120L || win[2L] == 88L) && vml_is_hex_digit(win[3L])) {
    k <- 3L
    while (k <= m && (k - 3L) < 6L && vml_is_hex_digit(win[k])) k <- k + 1L
    body_len <- k - 1L
    numeric_ref <- TRUE
    hex_ref <- TRUE
  } else if (m >= 2L && vml_is_ascii_letter(win[1L]) && vml_is_ascii_alnum(win[2L])) {
    k <- 2L
    while (k <= m && (k - 2L) < 7L && vml_is_ascii_alnum(win[k])) k <- k + 1L
    body_len <- k - 1L
  } else {
    return(NULL)
  }
  has_semi <- (body_len + 1L <= m) && win[body_len + 1L] == VML_SEMI
  body <- vml_slice(win, 1L, body_len)
  next_index <- amp_index + 1L + body_len + (if (has_semi) 1L else 0L)

  if (numeric_ref) {
    digits <- vml_slice(body, if (hex_ref) 3L else 2L, body_len)
    value <- 0
    base <- if (hex_ref) 16 else 10
    for (d in digits) value <- value * base + (if (hex_ref) vml_hex_value(d) else d - 48L)
    if (value > 0x10FFFF) return(NULL)
    if (value >= 0xD800 && value <= 0xDFFF) return(NULL)
    return(list(cps = as.integer(value), next_index = next_index))
  }
  name <- rawToChar(as.raw(as.integer(vml_ascii_lower(body))))
  if (!nzchar(name)) return(NULL)
  value <- VML_ENTITIES[[name]]
  if (is.null(value)) return(NULL)
  list(cps = as.integer(value), next_index = next_index)
}

# A buffer of code point runs, so that text is assembled in amortised constant time instead of
# growing a vector once per character.
vml_buf_new <- function() {
  b <- new.env(parent = emptyenv())
  b$items <- vector("list", 64L)
  b$n <- 0L
  b$cap <- 64L
  b
}

vml_buf_push <- function(b, cps) {
  if (length(cps) == 0L) return(invisible(NULL))
  if (b$n == b$cap) {
    b$cap <- b$cap * 2L
    length(b$items) <- b$cap
  }
  b$n <- b$n + 1L
  b$items[[b$n]] <- as.integer(cps)
  invisible(NULL)
}

vml_buf_value <- function(b) {
  if (b$n == 0L) return(integer(0))
  unlist(b$items[seq_len(b$n)], use.names = FALSE)
}

vml_tag_name <- function(raw) {
  n <- length(raw)
  i <- 1L
  if (n >= 1L && raw[1L] == VML_SLASH) i <- 2L
  while (i <= n && vml_is_js_space_cp(raw[i])) i <- i + 1L
  if (i > n) return("")
  if (!vml_is_ascii_letter(raw[i])) return("")
  j <- i
  while (j <= n && (vml_is_ascii_alnum(raw[j]) || raw[j] == VML_COLON || raw[j] == VML_DASH)) j <- j + 1L
  rawToChar(as.raw(as.integer(vml_ascii_lower(raw[i:(j - 1L)]))))
}

# /\\bhref\\s*=\\s*("..."|'...'|[^\\s>]+)/i, scanned left to right, first match wins.
vml_find_href <- function(raw) {
  n <- length(raw)
  if (n == 0L) return(integer(0))
  hay <- vml_ascii_lower(raw)
  needle <- A("href")
  start <- 1L
  repeat {
    p <- vml_find_seq(hay, needle, start)
    if (is.na(p)) return(integer(0))
    if (p > 1L && vml_is_word_cp(raw[p - 1L])) { start <- p + 1L; next }
    q <- p + length(needle)
    while (q <= n && vml_is_js_space_cp(raw[q])) q <- q + 1L
    if (q > n || raw[q] != VML_EQUALS) { start <- p + 1L; next }
    q <- q + 1L
    while (q <= n && vml_is_js_space_cp(raw[q])) q <- q + 1L
    if (q > n || raw[q] == VML_GT) { start <- p + 1L; next }
    if (raw[q] == VML_DQUOTE || raw[q] == VML_SQUOTE) {
      close <- vml_find_cp(raw, raw[q], q + 1L)
      if (is.na(close)) { start <- p + 1L; next }
      return(vml_slice(raw, q + 1L, close - 1L))
    }
    e <- q
    while (e <= n && !vml_is_js_space_cp(raw[e]) && raw[e] != VML_GT) e <- e + 1L
    return(vml_slice(raw, q, e - 1L))
  }
}

# ^[A-Za-z][A-Za-z0-9+.-]*: - "absolute" is a scheme test, not URL resolution.
vml_href_is_absolute <- function(href) {
  n <- length(href)
  if (n < 2L) return(FALSE)
  if (!vml_is_ascii_letter(href[1L])) return(FALSE)
  i <- 2L
  while (i <= n) {
    cp <- href[i]
    if (cp == VML_COLON) return(TRUE)
    if (!(vml_is_ascii_alnum(cp) || cp == 43L || cp == 46L || cp == VML_DASH)) return(FALSE)
    i <- i + 1L
  }
  FALSE
}

vml_extract_cps <- function(src, base_url) {
  # base_url is deliberately unused: the contract says href is reported verbatim, and resolving a
  # URL is a URI question, not a text question.
  invisible(base_url)
  if (length(src) == 0L) {
    return(list(title = integer(0), text = integer(0), links = list(), images = 0L))
  }
  # Pass order follows the reference implementation, not the numbering in the contract's section 3:
  # the CDATA bodies are hidden first (so nothing can mistake them for markup), then comments and
  # doctypes go, and the removed elements go last. The two orders differ only for an input where a
  # comment or doctype sits inside a removed element, or a CDATA body contains a comment opener; the
  # corpus cannot see the difference, and the reference's order is the one all implementations share.
  hidden <- vml_cdata_hide(src)
  src <- hidden$src
  cdata <- hidden$bodies
  src <- vml_comment_pass(src)
  src <- vml_doctype_pass(src)
  src <- vml_remove_elements(src)

  st <- new.env(parent = emptyenv())
  st$in_title <- FALSE
  st$title_seen <- FALSE
  st$text <- vml_buf_new()
  st$title <- vml_buf_new()
  st$pending <- NULL
  st$images <- 0L
  st$links <- list()
  st$links_n <- 0L

  push_text <- function(cps) {
    if (length(cps) == 0L) return(invisible(NULL))
    if (st$in_title) {
      # While a <title> is open its text belongs to the title and to nothing else: not to the body,
      # and not to an anchor that happens to contain it.
      vml_buf_push(st$title, cps)
      return(invisible(NULL))
    }
    vml_buf_push(st$text, cps)
    if (!is.null(st$pending)) vml_buf_push(st$pending$buf, cps)
    invisible(NULL)
  }
  close_pending <- function() {
    if (is.null(st$pending)) return(invisible(NULL))
    st$links_n <- st$links_n + 1L
    st$links[[st$links_n]] <- list(href = st$pending$href, absolute = st$pending$absolute,
                                   text = vml_buf_value(st$pending$buf))
    st$pending <- NULL
    invisible(NULL)
  }

  n <- length(src)
  special <- which(src == VML_LT | src == VML_AMP)
  i <- 1L
  while (i <= n) {
    cp <- src[i]
    handled <- FALSE

    if (cp == VML_LT && i < n && (vml_is_ascii_letter(src[i + 1L]) || src[i + 1L] == VML_SLASH || src[i + 1L] == VML_BANG)) {
      j <- i + 1L
      quote <- 0L
      while (j <= n) {
        cj <- src[j]
        if (quote != 0L) {
          if (cj == quote) quote <- 0L
        } else if (cj == VML_DQUOTE || cj == VML_SQUOTE) {
          quote <- cj
        } else if (cj == VML_GT) break
        j <- j + 1L
      }
      if (j <= n) {
        raw <- vml_slice(src, i + 1L, j - 1L)
        i_next <- j + 1L
      } else {
        # An input that ends inside a tag: the incomplete tag is dropped, including the characters of
        # its name, the way a browser's eof-in-tag state drops it - so it contributes no newline, no
        # link and no image. ("<p" is the empty string, not "\n".)
        i <- n + 1L
        next
      }
      closing <- length(raw) >= 1L && raw[1L] == VML_SLASH
      name <- vml_tag_name(raw)

      if (identical(name, "title")) {
        if (!closing && !st$title_seen) {
          st$in_title <- TRUE
          st$title_seen <- TRUE
        } else if (closing && st$in_title) {
          st$in_title <- FALSE
        }
        i <- i_next
        next
      }
      if (identical(name, "img") && !closing) st$images <- st$images + 1L
      if (identical(name, "a")) {
        if (!closing) {
          # HTML has no nested anchors: a browser closes the open one and starts the new one, so the
          # outer link is reported with the text it had collected and the inner becomes the open one.
          if (!is.null(st$pending)) close_pending()
          href <- vml_find_href(raw)
          pend <- new.env(parent = emptyenv())
          pend$href <- href
          pend$absolute <- vml_href_is_absolute(href)
          pend$buf <- vml_buf_new()
          st$pending <- pend
        } else {
          close_pending()
        }
        i <- i_next
        next
      }
      if (name %in% VML_NEWLINE_TAGS) push_text(10L)
      i <- i_next
      next
    }

    if (cp == VML_AMP) {
      dec <- vml_decode_entity(src, i)
      if (!is.null(dec)) {
        push_text(dec$cps)
        i <- dec$next_index
        handled <- TRUE
      }
    }
    if (handled) next

    # a run of literal text up to the next '<' or '&'
    k <- findInterval(i, special) + 1L
    end <- if (k <= length(special)) special[k] else n + 1L
    push_text(vml_slice(src, i, end - 1L))
    i <- end
  }

  # an anchor still open at end of input is reported with the text it collected
  close_pending()

  links <- st$links[seq_len(st$links_n)]
  links <- lapply(links, function(l) {
    list(href = l$href, absolute = l$absolute, text = vml_cdata_restore(l$text, cdata))
  })
  list(title = vml_cdata_restore(vml_buf_value(st$title), cdata),
       text = vml_cdata_restore(vml_buf_value(st$text), cdata),
       links = links, images = st$images)
}

# ---------------------------------------------------------------------------------------------
# 6. text.fingerprint (docs/WORKERS.md section 4)
#
#    FNV-1a over 64 bits with no 64-bit integer type: the accumulator is two 32-bit words, and the
#    multiply by the FNV prime is done in base 2^16. With P = 16777216 * 2^16 + 435, the four limb
#    products are at most 65535 * 16777216 ~= 1.1e12, so every intermediate value is an exact double
#    and the carry chain never rounds. (h * P) mod 2^64 is then just the low four limbs.
# ---------------------------------------------------------------------------------------------

VML_FNV_PRIME_HI <- 16777216      # floor(1099511628211 / 2^16)
VML_FNV_PRIME_LO <- 435           # 1099511628211 mod 2^16
VML_FNV_OFFSET_HI <- 3421674724   # floor(14695981039346656037 / 2^32)
VML_FNV_OFFSET_LO <- 2216829733   # 14695981039346656037 mod 2^32
VML_CJK_RANGES <- list(c(0x3400L, 0x4DBFL), c(0x4E00L, 0x9FFFL), c(0xF900L, 0xFAFFL),
                       c(0x3040L, 0x30FFL), c(0xAC00L, 0xD7AFL))

vml_punct_cps <- function() A("!?,.;:'\"()[]{}<>-_/\\|*+=~`@#$%^&")
VML_PUNCT <- vml_punct_cps()

vml_is_cjk_mask <- function(cps) {
  m <- rep(FALSE, length(cps))
  for (r in VML_CJK_RANGES) m <- m | (cps >= r[1L] & cps <= r[2L])
  m
}

vml_tokenize_token <- function(piece) {
  m <- piece %in% VML_PUNCT
  n <- length(piece)
  a <- 1L
  while (a <= n && m[a]) a <- a + 1L
  if (a > n) return(list())
  b <- n
  while (b >= a && m[b]) b <- b - 1L
  t <- piece[a:b]
  if (length(t) == 0L) return(list())
  if (all(t %in% VML_PUNCT)) return(list())
  cjk <- vml_is_cjk_mask(t)
  out <- list()
  k <- 0L
  start <- 1L
  repeat {
    if (start > length(t)) break
    cls <- cjk[start]
    end <- start
    while (end + 1L <= length(t) && cjk[end + 1L] == cls) end <- end + 1L
    run <- t[start:end]
    if (cls) {
      if (length(run) == 1L) {
        k <- k + 1L
        out[[k]] <- run
      } else {
        for (p in seq_len(length(run) - 1L)) {
          k <- k + 1L
          out[[k]] <- c(run[p], run[p + 1L])
        }
      }
    } else {
      k <- k + 1L
      out[[k]] <- run
    }
    start <- end + 1L
  }
  out
}

vml_tokens_of <- function(cps) {
  out <- list()
  k <- 0L
  n <- length(cps)
  if (n == 0L) return(out)
  breaks <- c(0L, which(cps == VML_SPACE), n + 1L)
  for (t in seq_len(length(breaks) - 1L)) {
    piece <- vml_slice(cps, breaks[t] + 1L, breaks[t + 1L] - 1L)
    if (length(piece) == 0L) next
    toks <- vml_tokenize_token(piece)
    for (tk in toks) {
      k <- k + 1L
      out[[k]] <- tk
    }
  }
  out
}

vml_join_tokens <- function(toks) {
  m <- length(toks)
  total <- sum(vapply(toks, length, integer(1))) + m - 1L
  out <- integer(total)
  p <- 1L
  for (k in seq_len(m)) {
    v <- toks[[k]]
    L <- length(v)
    if (L > 0L) out[p:(p + L - 1L)] <- v
    p <- p + L
    if (k < m) {
      out[p] <- VML_SPACE
      p <- p + 1L
    }
  }
  out
}

vml_shingles_of <- function(tokens) {
  n <- length(tokens)
  if (n == 0L) return(list())
  if (n < 3L) return(list(vml_join_tokens(tokens)))
  lapply(seq_len(n - 2L), function(i) vml_join_tokens(tokens[i:(i + 2L)]))
}

vml_fnv1a64_cps <- function(cps) {
  hi <- VML_FNV_OFFSET_HI
  lo <- VML_FNV_OFFSET_LO
  bytes <- as.integer(vml_utf8_encode(cps))
  for (byte in bytes) {
    lo <- lo - (lo %% 256) + bitwXor(as.integer(lo %% 256), byte)
    a <- hi %/% 65536
    b <- hi %% 65536
    cc <- lo %/% 65536
    d <- lo %% 65536
    t0 <- d * VML_FNV_PRIME_LO
    t1 <- cc * VML_FNV_PRIME_LO + d * VML_FNV_PRIME_HI
    t2 <- b * VML_FNV_PRIME_LO + cc * VML_FNV_PRIME_HI
    t3 <- a * VML_FNV_PRIME_LO + b * VML_FNV_PRIME_HI
    d2 <- t0 %% 65536
    carry <- t0 %/% 65536
    v <- t1 + carry
    c2 <- v %% 65536
    carry <- v %/% 65536
    v <- t2 + carry
    b2 <- v %% 65536
    carry <- v %/% 65536
    v <- t3 + carry
    a2 <- v %% 65536
    hi <- a2 * 65536 + b2
    lo <- c2 * 65536 + d2
  }
  list(hi = hi, lo = lo)
}

vml_hex64 <- function(hi, lo) {
  # 16 hex digits, most significant first: hi fills positions 1-8, lo positions 9-16.
  digs <- character(16L)
  x <- hi
  for (k in 8:1) {
    digs[k] <- VML_HEX_DIGITS[[as.integer(x %% 16) + 1L]]
    x <- x %/% 16
  }
  x <- lo
  for (k in 16:9) {
    digs[k] <- VML_HEX_DIGITS[[as.integer(x %% 16) + 1L]]
    x <- x %/% 16
  }
  paste(digs, collapse = "")
}

vml_fingerprint_cps <- function(cps) {
  tokens <- vml_tokens_of(cps)
  shingles <- vml_shingles_of(tokens)
  counters <- integer(64L)
  for (s in shingles) {
    h <- vml_fnv1a64_cps(s)
    for (bit in 0:31) {
      set <- ((h$lo %/% (2^bit)) %% 2) >= 1
      counters[bit + 1L] <- counters[bit + 1L] + (if (set) 1L else -1L)
    }
    for (bit in 32:63) {
      set <- ((h$hi %/% (2^(bit - 32L))) %% 2) >= 1
      counters[bit + 1L] <- counters[bit + 1L] + (if (set) 1L else -1L)
    }
  }
  out_lo <- 0
  out_hi <- 0
  for (bit in 0:31) if (counters[bit + 1L] > 0L) out_lo <- out_lo + 2^bit
  for (bit in 32:63) if (counters[bit + 1L] > 0L) out_hi <- out_hi + 2^(bit - 32L)
  list(simhash = vml_hex64(out_hi, out_lo), tokens = length(tokens), shingles = length(shingles))
}

# ---------------------------------------------------------------------------------------------
# 7. The protocol (docs/WORKERS.md section 1)
# ---------------------------------------------------------------------------------------------

vml_descriptor_node <- function(capability) {
  vml_jobj(list(
    protocol = vml_jnum(1L),
    capability = vml_jstr(A(capability)),
    language = vml_jstr(A("r")),
    impl = vml_jstr(A("table-driven")),
    runtime = vml_jstr(vml_utf8_decode(charToRaw(R.version.string))),
    deterministic = vml_jbool(TRUE)
  ))
}

vml_error_node <- function(id_node, code, message) {
  vml_jobj(list(id = id_node, ok = vml_jbool(FALSE),
                error = vml_jobj(list(code = vml_jstr(A(code)), message = vml_jstr(A(message))))))
}

vml_invoke <- function(capability, input_node) {
  if (identical(capability, "text.normalize")) {
    text <- vml_as_string(vml_obj_get(input_node, "text"))
    if (is.null(text)) return(list(ok = FALSE, code = "bad-input", message = "input.text must be a string"))
    return(list(ok = TRUE, output = vml_jobj(list(text = vml_jstr(vml_normalize_cps(text))))))
  }
  if (identical(capability, "text.extract")) {
    html <- vml_as_string(vml_obj_get(input_node, "html"))
    if (is.null(html)) return(list(ok = FALSE, code = "bad-input", message = "input.html must be a string"))
    base_url <- vml_obj_get(input_node, "baseUrl") # accepted, reported back nowhere, never used
    r <- vml_extract_cps(html, base_url)
    link_nodes <- lapply(r$links, function(l) {
      vml_jobj(list(href = vml_jstr(l$href), absolute = vml_jbool(l$absolute),
                    text = vml_jstr(l$text)))
    })
    return(list(ok = TRUE, output = vml_jobj(list(
      title = vml_jstr(r$title), text = vml_jstr(r$text),
      links = vml_jarr(link_nodes), images = vml_jnum(r$images)))))
  }
  if (identical(capability, "text.fingerprint")) {
    text <- vml_as_string(vml_obj_get(input_node, "text"))
    if (is.null(text)) return(list(ok = FALSE, code = "bad-input", message = "input.text must be a string"))
    f <- vml_fingerprint_cps(text)
    return(list(ok = TRUE, output = vml_jobj(list(
      simhash = vml_jstr(A(f$simhash)), tokens = vml_jnum(f$tokens), shingles = vml_jnum(f$shingles)))))
  }
  list(ok = FALSE, code = "unsupported", message = paste0("unsupported capability ", capability))
}

# Returns list(response = <code points or NULL>, stop = <logical>).
vml_handle_line <- function(cps, capability) {
  node <- tryCatch(vml_json_reader(cps), error = function(e) NULL)
  if (is.null(node)) {
    return(list(response = vml_json_encode(vml_error_node(vml_jnull(), "bad-input", "request is not JSON")),
                stop = FALSE))
  }
  id_node <- vml_obj_get(node, "id")
  if (is.null(id_node)) id_node <- vml_jnull()
  op <- vml_as_string(vml_obj_get(node, "op"))
  op_name <- if (is.null(op)) "<missing>" else rawToChar(as.raw(as.integer(op)))

  if (!is.null(op) && identical(op_name, "shutdown")) {
    # The contract shows {"id":<id>,"ok":true} for shutdown and nothing more. (The JavaScript
    # reference answers with an extra {"bye":true} output object; the Go worker reports the same
    # difference in its README, and this one follows the contract.)
    return(list(response = vml_json_encode(vml_jobj(list(id = id_node, ok = vml_jbool(TRUE)))),
                stop = TRUE))
  }
  if (!is.null(op) && identical(op_name, "describe")) {
    return(list(response = vml_json_encode(vml_jobj(list(
      id = id_node, ok = vml_jbool(TRUE), worker = vml_descriptor_node(capability)))), stop = FALSE))
  }
  if (is.null(op) || !identical(op_name, "invoke")) {
    return(list(response = vml_json_encode(vml_error_node(id_node, "unsupported",
                                                          paste0("unknown op ", op_name))), stop = FALSE))
  }

  requested <- vml_as_string(vml_obj_get(node, "capability"))
  requested_name <- if (is.null(requested)) NULL else rawToChar(as.raw(as.integer(requested)))
  if (!is.null(requested_name) && !identical(requested_name, capability)) {
    return(list(response = vml_json_encode(vml_error_node(
      id_node, "unsupported",
      paste0("this worker implements ", capability, ", not ", requested_name))), stop = FALSE))
  }
  input_node <- vml_obj_get(node, "input")
  if (is.null(input_node)) input_node <- vml_jobj(list())
  res <- tryCatch(vml_invoke(capability, input_node), error = function(e) {
    list(ok = FALSE, code = "internal", message = paste0("internal error: ", conditionMessage(e)))
  })
  if (isTRUE(res$ok)) {
    return(list(response = vml_json_encode(vml_jobj(list(id = id_node, ok = vml_jbool(TRUE),
                                                         output = res$output))), stop = FALSE))
  }
  list(response = vml_json_encode(vml_error_node(id_node, res$code, res$message)), stop = FALSE)
}

vml_serve <- function(capability) {
  incon <- file("stdin", "rb")
  on.exit(try(close(incon), silent = TRUE), add = TRUE)
  repeat {
    line <- readLines(incon, n = 1L, warn = FALSE)
    if (length(line) == 0L) break # EOF
    if (!nzchar(line)) next
    cps <- vml_utf8_decode(charToRaw(line))
    outcome <- vml_handle_line(cps, capability)
    if (!is.null(outcome$response)) {
      # One write, one flush, before the next read. Without the flush a piped stdout would hold a
      # correct answer until the process exits and the host would see a timeout, not an answer.
      cat(vml_to_native_bytes_string(outcome$response), "\n", sep = "", file = stdout())
      flush(stdout())
    }
    if (isTRUE(outcome$stop)) break
  }
  invisible(NULL)
}

# ---------------------------------------------------------------------------------------------
# 8. --selfcheck: the built-in case list. One English line per case, an "N/M checks passed"
#    summary, exit non-zero on failure, and no protocol traffic on stdout in this mode.
# ---------------------------------------------------------------------------------------------

VML_SELFCHECK_NOTE <- new.env(parent = emptyenv())

vml_selfcheck_cases <- function() {
  cases <- list()

  add <- function(name, fn) cases[[length(cases) + 1L]] <<- list(name = name, fn = fn)
  # Compares code point vectors and, on a mismatch, leaves an ASCII-safe expected/actual note for
  # the report: a console in a non-UTF-8 code page cannot be trusted to show CJK correctly.
  eq_cps <- function(actual, expected) {
    ok <- length(actual) == length(expected) && all(actual == expected)
    if (!ok) {
      VML_SELFCHECK_NOTE$text <- paste0("expected ", vml_repr(expected), ", got ", vml_repr(actual))
    }
    ok
  }

  add("normalize lowercases ASCII without its own case tables", function() {
    eq_cps(vml_normalize_cps(A("Hello, World.")), A("hello, world."))
  })
  add("normalize maps full-width ASCII (U+FF01-U+FF5E) to ASCII", function() {
    src <- as.integer(c(0xFF21L, 0xFF22L, 0xFF23L, 0xFF11L, 0xFF12L, 0xFF13L, 0xFF01L))
    eq_cps(vml_normalize_cps(src), A("abc123!"))
  })
  add("normalize deletes the zero-width space U+200B", function() {
    eq_cps(vml_normalize_cps(as.integer(c(0x61L, 0x200BL, 0x62L))), A("ab"))
  })
  add("normalize deletes combining marks so NFD equals NFC", function() {
    eq_cps(vml_normalize_cps(as.integer(c(0x65L, 0x301L))), A("e"))
  })
  add("normalize maps U+2014 to a hyphen and U+2026 to three dots", function() {
    src <- as.integer(c(0x61L, 0x2014L, 0x62L, 0x2026L, 0x63L))
    eq_cps(vml_normalize_cps(src), A("a-b...c"))
  })
  add("normalize is idempotent on an accent, full-width, zero-width mix", function() {
    src <- as.integer(c(0x2018L, 0xC9L, 0x2019L, 0x20L, 0xFF21L, 0xFF22L, 0xFF23L, 0x20L, 0x20L,
                        0x141L, 0xF3L, 0x64L, 0x17AL, 0x200BL))
    once <- vml_normalize_cps(src)
    eq_cps(vml_normalize_cps(once), once)
  })
  add("normalize leaves Han, kana and Hangul untouched", function() {
    src <- as.integer(c(0x5DF2L, 0x7ECFL, 0x5F00L, 0x64ADL, 0x4E86L, 0x20L, 0xD55CL, 0xAD6DL,
                        0xC5B4L, 0x20L, 0x30C6L, 0x30B9L, 0x30C8L))
    eq_cps(vml_normalize_cps(src), src)
  })
  add("normalize leaves Cyrillic and Arabic untouched", function() {
    src <- as.integer(c(0x41FL, 0x440L, 0x438L, 0x432L, 0x435L, 0x442L, 0x20L, 0x645L, 0x631L,
                        0x62DL, 0x628L, 0x627L))
    eq_cps(vml_normalize_cps(src), src)
  })
  add("normalize of the empty string is the empty string", function() {
    eq_cps(vml_normalize_cps(integer(0)), integer(0))
  })
  add("normalize trims and collapses whitespace to single spaces", function() {
    eq_cps(vml_normalize_cps(A("  a \t\n b \r\n  c  ")), A("a b c"))
  })
  add("extract drops script and style with their content", function() {
    r <- vml_extract_cps(A("<p>x</p><script>var a=1</script>"), NULL)
    eq_cps(r$text, A("\nx\n")) && r$images == 0L && length(r$links) == 0L
  })
  add("extract drops an unclosed tag at end of input", function() {
    eq_cps(vml_extract_cps(A("<p>a<b>b"), NULL)$text, A("\nab"))
  })
  add("extract decodes a named entity without its semicolon", function() {
    eq_cps(vml_extract_cps(A("a &amp b"), NULL)$text, A("a & b"))
  })
  add("extract decodes a decimal numeric entity (&#8212;)", function() {
    eq_cps(vml_extract_cps(A("&#8212;"), NULL)$text, as.integer(0x2014L))
  })
  add("extract decodes a hex numeric entity (&#x2014;)", function() {
    eq_cps(vml_extract_cps(A("&#x2014;"), NULL)$text, as.integer(0x2014L))
  })
  add("extract leaves an unknown entity and &copy2024 literal", function() {
    eq_cps(vml_extract_cps(A("&unknown; &copy2024"), NULL)$text, A("&unknown; &copy2024"))
  })
  add("extract closes the outer anchor when a nested one opens", function() {
    r <- vml_extract_cps(A("<a href=\"/one\">one<a href=\"/two\">two"), NULL)
    length(r$links) == 2L && eq_cps(r$links[[1L]]$href, A("/one")) &&
      eq_cps(r$links[[1L]]$text, A("one")) && !r$links[[1L]]$absolute &&
      eq_cps(r$links[[2L]]$href, A("/two")) && eq_cps(r$links[[2L]]$text, A("two")) &&
      eq_cps(r$text, A("onetwo"))
  })
  add("extract keeps CDATA as literal text and does not re-parse it", function() {
    r <- vml_extract_cps(A("<![CDATA[<b>raw</b>]]>"), NULL)
    eq_cps(r$text, A("<b>raw</b>")) && r$images == 0L
  })
  add("extract keeps an unclosed CDATA section to the end of the input", function() {
    eq_cps(vml_extract_cps(A("<![CDATA[unclosed"), NULL)$text, A("unclosed"))
  })
  add("extract drops an incomplete tag at eof, name characters included", function() {
    r1 <- vml_extract_cps(A("<p"), NULL)
    r2 <- vml_extract_cps(A("<p>abc<b"), NULL)
    length(r1$text) == 0L && eq_cps(r2$text, A("\nabc"))
  })
  add("extract keeps a lone < at eof as literal text", function() {
    eq_cps(vml_extract_cps(A("a<"), NULL)$text, A("a<"))
  })
  add("extract gives a title inside an anchor to the title alone", function() {
    r <- vml_extract_cps(A("<a href=\"/x\"><title>T</title>t</a>"), NULL)
    eq_cps(r$title, A("T")) && eq_cps(r$text, A("t")) && eq_cps(r$links[[1L]]$text, A("t"))
  })
  add("extract keeps the title out of the text and decodes entities in it", function() {
    r <- vml_extract_cps(A("<title>A &amp; B</title><p>x</p>"), NULL)
    eq_cps(r$title, A("A & B")) && eq_cps(r$text, A("\nx\n"))
  })
  add("extract counts img tags and keeps a > inside a quoted attribute", function() {
    r <- vml_extract_cps(A("<a href=\"x>y\">z</a><img src=a><IMG src=b>"), NULL)
    r$images == 2L && eq_cps(r$links[[1L]]$href, A("x>y")) && eq_cps(r$text, A("z"))
  })
  add("extract of the empty document is empty, not null", function() {
    r <- vml_extract_cps(integer(0), NULL)
    length(r$text) == 0L && length(r$title) == 0L && r$images == 0L && length(r$links) == 0L
  })
  add("fingerprint of one token is that token's own FNV-1a hash", function() {
    f <- vml_fingerprint_cps(A("x"))
    identical(f$simhash, "af63f54c86021707") && f$tokens == 1L && f$shingles == 1L
  })
  add("fingerprint of empty text is all zero bits", function() {
    f <- vml_fingerprint_cps(integer(0))
    identical(f$simhash, "0000000000000000") && f$tokens == 0L && f$shingles == 0L
  })
  add("fingerprint ignores punctuation-only tokens", function() {
    f <- vml_fingerprint_cps(A("-- !! ???"))
    f$tokens == 0L && f$shingles == 0L && identical(f$simhash, "0000000000000000")
  })
  add("fingerprint turns a 4-character CJK run into 3 bigrams", function() {
    src <- as.integer(c(0x5DF2L, 0x7ECFL, 0x5F00L, 0x64ADL))
    f <- vml_fingerprint_cps(src)
    f$tokens == 3L && f$shingles == 1L
  })
  add("fingerprint matches the reviewed snapshot for three shingles", function() {
    a <- vml_fingerprint_cps(A("a b c"))
    b <- vml_fingerprint_cps(as.integer(c(0x5DF2L, 0x7ECFL, 0x20L, 0x5DF2L, 0x7ECFL)))
    c3 <- vml_fingerprint_cps(A(paste("the quick brown fox jumps over the lazy dog while the diligent",
                                      "vtuber monitor watches every source it was told to watch and writes",
                                      "a dated report about everything it saw and everything it could not see",
                                      "because the network refused to cooperate again today")))
    identical(a$simhash, "69cf480885ad45af") && a$tokens == 3L && a$shingles == 1L &&
      identical(b$simhash, "27bfb7b6385da4c5") && b$tokens == 2L && b$shingles == 1L &&
      identical(c3$simhash, "9fe9e24f2a6ef5ca") && c3$tokens == 45L && c3$shingles == 43L
  })
  add("fingerprint counts overlapping trigram shingles", function() {
    f <- vml_fingerprint_cps(A("a b c d"))
    f$tokens == 4L && f$shingles == 2L
  })

  cases
}

vml_run_selfcheck <- function() {
  cases <- vml_selfcheck_cases()
  passed <- 0L
  for (cs in cases) {
    detail <- ""
    VML_SELFCHECK_NOTE$text <- NULL
    res <- tryCatch(cs$fn(), error = function(e) {
      detail <<- paste0(": ", conditionMessage(e))
      NULL
    })
    ok <- isTRUE(res)
    if (!ok && !nzchar(detail) && !is.null(VML_SELFCHECK_NOTE$text)) {
      detail <- paste0(": ", VML_SELFCHECK_NOTE$text)
    }
    cat(if (ok) "[ok]   " else "[FAIL] ", cs$name, detail, "\n", sep = "")
    if (ok) passed <- passed + 1L
  }
  cat(passed, "/", length(cases), " checks passed\n", sep = "")
  flush(stdout())
  if (passed != length(cases)) quit(save = "no", status = 1L, runLast = FALSE)
  invisible(TRUE)
}

# ---------------------------------------------------------------------------------------------
# 9. Entry point
# ---------------------------------------------------------------------------------------------

vml_usage <- function() {
  paste0("usage: vmltext.R --capability <", paste(VML_CAPABILITIES, collapse = "|"), "> [--selfcheck]")
}

vml_main <- function() {
  argv <- commandArgs(trailingOnly = TRUE)
  selfcheck <- FALSE
  capability <- NULL
  i <- 1L
  while (i <= length(argv)) {
    a <- argv[[i]]
    if (identical(a, "--selfcheck")) {
      selfcheck <- TRUE
      i <- i + 1L
    } else if (identical(a, "--capability")) {
      if (i == length(argv)) {
        vml_diag("error: --capability requires a capability name")
        vml_diag(vml_usage())
        quit(save = "no", status = 2L, runLast = FALSE)
      }
      capability <- argv[[i + 1L]]
      i <- i + 2L
    } else {
      vml_diag("error: unrecognised argument '", a, "'")
      vml_diag(vml_usage())
      quit(save = "no", status = 2L, runLast = FALSE)
    }
  }

  vml_load_tables()

  if (selfcheck) {
    vml_run_selfcheck()
    quit(save = "no", status = 0L, runLast = FALSE)
  }
  if (is.null(capability)) {
    vml_diag("error: --capability <name> is required")
    vml_diag(vml_usage())
    quit(save = "no", status = 2L, runLast = FALSE)
  }
  if (!(capability %in% VML_CAPABILITIES)) {
    vml_diag("error: unknown capability '", capability, "'; this artifact implements ",
             paste(VML_CAPABILITIES, collapse = ", "))
    vml_diag(vml_usage())
    quit(save = "no", status = 2L, runLast = FALSE)
  }

  vml_serve(capability)
  quit(save = "no", status = 0L, runLast = FALSE)
}

if (!interactive()) vml_main()
