// reports.js — report & run storage
import fs from 'node:fs';
import path from 'node:path';
import { resolveDir } from './config.js';
import { diffLines, diffStats, diffHunks } from './diff.js';
import { buildDocx } from './office.js';

const DATE = () => new Date().toISOString().slice(0, 10);
const STAMP = () => new Date().toISOString().replace(/[:.]/g, '-');

export function ensureDirs(cfg) {
  for (const key of ['reportsDir', 'feedsDir', 'logsDir', 'watchDir']) {
    fs.mkdirSync(resolveDir(cfg, key), { recursive: true });
  }
}

// ───────────────────────────────────────── report output format
// Daily intel no longer writes .md by default: it switched to a format that looks good in VSCode.
// - html : a self-styled single-file page (previewable in VSCode, no plugin needed)
// - adoc : AsciiDoc (previewable in VSCode with an extension; readable as plain text too)
// - md   : the old behaviour, kept for compatibility
// - json : structured, program-friendly
export const REPORT_FORMATS = ['html', 'adoc', 'md', 'json'];
const REPORT_EXTS = REPORT_FORMATS;

/** The report primary file's extension (without the dot) */
export function reportFormat(cfg) {
  const f = String(cfg?.reports?.format ?? 'html').toLowerCase().replace(/^\./, '');
  return REPORT_FORMATS.includes(f) ? f : 'html';
}

const REPORT_CSS = `:root { color-scheme: light dark; }
body { max-width: 900px; margin: 40px auto; padding: 0 20px; font: 15px/1.7 -apple-system, "Segoe UI", "Microsoft YaHei", sans-serif; }
h1,h2,h3 { line-height: 1.3; border-bottom: 1px solid #8883; padding-bottom: .2em; }
code { background: #8881; padding: .1em .35em; border-radius: 4px; }
pre { background: #8881; padding: 12px; border-radius: 8px; overflow: auto; }
table { border-collapse: collapse; width: 100%; }
th,td { border: 1px solid #8884; padding: 6px 10px; text-align: left; }
blockquote { border-left: 3px solid #8886; margin: 0; padding-left: 12px; color: #8888; }
a { color: #3b82f6; }
footer { margin-top: 48px; font-size: 12px; color: #8888; }`;

/** markdown -> a complete HTML document (the report primary file and "export HTML" share the same styling) */
export function htmlShell(title, md, footer = `由 Vtuber's Monitor Link 导出 · ${new Date().toISOString()}`) {
  return `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${title}</title>
<style>
${REPORT_CSS}
</style>
</head>
<body>
${markdownToHtml(md)}
<footer>${footer}</footer>
</body>
</html>`;
}

/** markdown -> AsciiDoc: good enough (headings / lists / quotes / code blocks / links) */
export function markdownToAdoc(md) {
  const src = String(md ?? '').replace(/\r\n?/g, '\n');
  const out = [];
  let inFence = false;
  for (const line of src.split('\n')) {
    const fence = line.match(/^```\s*([A-Za-z0-9_+-]*)\s*$/);
    if (fence) {
      if (!inFence) {
        out.push(`[source,${fence[1] || 'text'}]`, '----');
        inFence = true;
      } else {
        out.push('----');
        inFence = false;
      }
      continue;
    }
    if (inFence) {
      out.push(line);
      continue;
    }
    const h = line.match(/^(#{1,6})\s+(.*)$/);
    if (h) {
      out.push('='.repeat(Math.min(h[1].length + 1, 6)) + ' ' + h[2]);
      continue;
    }
    if (/^\s*[-*+]\s+/.test(line)) {
      out.push(line.replace(/^(\s*)[-*+]\s+/, '$1* '));
      continue;
    }
    out.push(
      line
        .replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '$1 ($2)')
        .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)')
        .replace(/\*\*([^*]+)\*\*/g, '*$1*')
        .replace(/`([^`]+)`/g, '`$1`'),
    );
  }
  return out.join('\n');
}

/** The run's source data file (accumulating several runs of the same day); the primary file is rendered from it */
function sourceName(mode, date) {
  return `${mode === 'merch' ? 'merch-' : ''}${date}.json`;
}

function renderPrimary(cfg, source) {
  const md = source.runs.map((r) => r.markdown).join('\n\n---\n\n');
  const fmt = reportFormat(cfg);
  const title = `${source.mode === 'merch' ? '周边' : 'Vtuber 情报'} ${source.date}`;
  if (fmt === 'adoc') {
    return `// generated by Vtuber's Monitor Link at ${source.generatedAt}\n// 用 VSCode + AsciiDoc 扩展预览；纯文本阅读亦可\n\n= ${title}\n\n${markdownToAdoc(md)}\n`;
  }
  if (fmt === 'md') {
    return `<!-- generated by Vtuber's Monitor Link at ${source.generatedAt} -->\n\n${md}\n`;
  }
  return htmlShell(title, md, `由 Vtuber's Monitor Link 生成 · ${source.generatedAt} · ${source.runs.length} 次运行`);
}

export function saveReport(cfg, { markdown, mode = 'daily', date = DATE() }) {
  const dir = resolveDir(cfg, 'reportsDir');
  fs.mkdirSync(dir, { recursive: true });
  const srcFile = path.join(dir, sourceName(mode, date));
  let source = { date, mode, generatedAt: new Date().toISOString(), format: reportFormat(cfg), runs: [] };
  if (fs.existsSync(srcFile)) {
    try {
      const prev = JSON.parse(fs.readFileSync(srcFile, 'utf8'));
      if (prev && Array.isArray(prev.runs)) source = { ...prev, runs: prev.runs };
    } catch {
      // a corrupt source file counts as the first run of the day; it must not block the report
    }
  }
  source.runs.push({ at: new Date().toISOString(), markdown });
  source.generatedAt = new Date().toISOString();
  source.format = reportFormat(cfg);

  const primary = path.join(dir, `${sourceName(mode, date).replace(/\.json$/, '')}.${source.format}`);
  const fmt = source.format;
  fs.writeFileSync(srcFile, JSON.stringify(source, null, 2), 'utf8');
  if (fmt === 'json') return srcFile;
  fs.writeFileSync(primary, renderPrimary(cfg, source), 'utf8');
  return primary;
}

export function saveFeedFiles(cfg, date, results) {
  const dir = path.join(resolveDir(cfg, 'feedsDir'), date);
  fs.mkdirSync(dir, { recursive: true });
  const index = [];
  for (const r of results) {
    if (!r.ok || !r.content) {
      index.push({ id: r.source.id, ok: false, error: r.error ?? r.note ?? null });
      continue;
    }
    const ext = r.ext ?? 'txt';
    const file = path.join(dir, `${r.source.id}.${ext}`);
    fs.writeFileSync(file, r.content, 'utf8');
    index.push({ id: r.source.id, ok: true, file: path.relative(resolveDir(cfg, 'feedsDir'), file), bytes: r.content.length });
    void file;
  }
  fs.writeFileSync(path.join(dir, '_index.json'), JSON.stringify(index, null, 2), 'utf8');
  return { dir, index };
}

export function listReports(cfg) {
  const dir = resolveDir(cfg, 'reportsDir');
  if (!fs.existsSync(dir)) return [];
  const fmt = reportFormat(cfg);
  return fs
    .readdirSync(dir)
    .filter((f) => REPORT_EXTS.some((e) => f.endsWith(`.${e}`)))
    // when the primary file itself is .json, it is the primary file and is no longer hidden away as a sidecar
    .filter((f) => !f.endsWith('.json') || fmt === 'json')
    .map((f) => {
      const st = fs.statSync(path.join(dir, f));
      const ext = path.extname(f).slice(1);
      return { name: f, ext, format: ext, bytes: st.size, mtime: st.mtime.toISOString() };
    })
    .sort((a, b) => (a.name < b.name ? 1 : -1));
}

/** Read a report's raw content (html is returned as-is for iframe rendering, other formats give text) */
export function readReport(cfg, name) {
  const safe = path.basename(name);
  const file = path.join(resolveDir(cfg, 'reportsDir'), safe);
  if (!fs.existsSync(file)) return null;
  return fs.readFileSync(file, 'utf8');
}

/** html -> plain text (the fallback when there is no source file; good enough for search and export) */
function htmlToText(html) {
  return String(html ?? '')
    .replace(/<(script|style)[\s\S]*?<\/\1>/gi, '')
    .replace(/<\/(p|div|li|h[1-6]|tr|blockquote|pre)>/gi, '\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/**
 * Get the markdown source text behind any report.
 * This is the key to "changing the format does not affect export/search/diff": every primary file is
 * rendered from a .json source.
 */
export function markdownSource(cfg, name) {
  const dir = resolveDir(cfg, 'reportsDir');
  const safe = path.basename(name);
  const file = path.join(dir, safe);
  if (!fs.existsSync(file)) return null;
  const raw = fs.readFileSync(file, 'utf8');
  if (safe.endsWith('.json')) {
    try {
      const j = JSON.parse(raw);
      if (Array.isArray(j.runs)) return j.runs.map((r) => r.markdown).join('\n\n---\n\n');
      if (typeof j.markdown === 'string') return j.markdown;
      return '';
    } catch {
      return raw;
    }
  }
  const sibling = path.join(dir, `${safe.replace(/\.[^.]+$/, '')}.json`);
  if (fs.existsSync(sibling)) {
    try {
      const j = JSON.parse(fs.readFileSync(sibling, 'utf8'));
      if (Array.isArray(j.runs)) return j.runs.map((r) => r.markdown).join('\n\n---\n\n');
    } catch {
      // fall through to the extension-based fallback below
    }
  }
  if (safe.endsWith('.md')) return raw;
  if (safe.endsWith('.adoc')) return raw.replace(/^\/\/.*$/gm, '');
  return htmlToText(raw);
}

export function runLogPath(cfg, label = 'run') {
  const dir = resolveDir(cfg, 'logsDir');
  fs.mkdirSync(dir, { recursive: true });
  return path.join(dir, `${label}-${STAMP()}.log`);
}

// ───────────────────────────────────────── intel items

/** Persist this run's structured intel items (the web card stream consumes this) */
export function saveItems(cfg, date, items, meta = {}) {
  const dir = path.join(resolveDir(cfg, 'feedsDir'), date);
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, '_items.json');
  const payload = { generatedAt: new Date().toISOString(), date, count: items.length, ...meta, items };
  // keep one copy of the previous result for the "this run vs last run" comparison; one copy only,
  // never piling up
  try {
    if (fs.existsSync(file)) fs.copyFileSync(file, path.join(dir, '_items-prev.json'));
  } catch {
    /* if it cannot be kept, so be it; it does not affect this write */
  }
  fs.writeFileSync(file, JSON.stringify(payload, null, 1), 'utf8');
  return file;
}

/** Read the intel items of the most recent run */
export function latestIntel(cfg, limit = 400) {
  const root = resolveDir(cfg, 'feedsDir');
  if (!fs.existsSync(root)) return { generatedAt: null, items: [], runs: [] };
  const days = fs
    .readdirSync(root)
    .filter((d) => /^\d{4}-\d{2}-\d{2}$/.test(d))
    .sort()
    .reverse();
  const runs = [];
  for (const d of days.slice(0, 30)) {
    const f = path.join(root, d, '_items.json');
    if (fs.existsSync(f)) {
      const st = fs.statSync(f);
      runs.push({ date: d, mtime: st.mtime.toISOString() });
    }
  }
  for (const d of days) {
    const f = path.join(root, d, '_items.json');
    if (!fs.existsSync(f)) continue;
    try {
      const j = JSON.parse(fs.readFileSync(f, 'utf8'));
      return { ...j, items: (j.items ?? []).slice(0, limit), runs };
    } catch {
      /* corrupt, keep looking further back */
    }
  }
  return { generatedAt: null, items: [], runs };
}

/** The previous run's intel items (used for the comparison) */
export function previousIntel(cfg) {
  const root = resolveDir(cfg, 'feedsDir');
  if (!fs.existsSync(root)) return { generatedAt: null, items: [] };
  const days = fs
    .readdirSync(root)
    .filter((d) => /^\d{4}-\d{2}-\d{2}$/.test(d))
    .sort()
    .reverse();
  for (const d of days) {
    const f = path.join(root, d, '_items-prev.json');
    if (!fs.existsSync(f)) continue;
    try {
      const j = JSON.parse(fs.readFileSync(f, 'utf8'));
      return { generatedAt: j.generatedAt ?? null, date: j.date ?? d, items: j.items ?? [] };
    } catch {
      /* ignore */
    }
  }
  return { generatedAt: null, items: [] };
}

/** This run vs last run: added / removed / still present / changed items */
export function diffIntel(cfg) {
  const cur = latestIntel(cfg, 1000);
  const prev = previousIntel(cfg);
  const prevMap = new Map((prev.items ?? []).map((i) => [i.id, i]));
  const curMap = new Map((cur.items ?? []).map((i) => [i.id, i]));

  const added = (cur.items ?? []).filter((i) => !prevMap.has(i.id));
  const removed = (prev.items ?? []).filter((i) => !curMap.has(i.id));
  const changed = [];
  for (const [id, now] of curMap) {
    const before = prevMap.get(id);
    if (!before) continue;
    if (String(before.text ?? '') === String(now.text ?? '')) continue;
    changed.push({ id, before, after: now });
  }
  // changes like a follower-count increase ("same id but the number moved") count as changes too
  return {
    current: { at: cur.generatedAt ?? null, date: cur.date ?? null, count: (cur.items ?? []).length },
    previous: { at: prev.generatedAt ?? null, date: prev.date ?? null, count: (prev.items ?? []).length },
    hasPrevious: (prev.items ?? []).length > 0,
    added,
    removed,
    changed,
  };
}

// ───────────────────────────────────────── star / read / flags

function flagsPath(cfg) {
  return path.join(resolveDir(cfg, 'feedsDir'), 'flags.json');
}

export function loadFlags(cfg) {
  try {
    const f = flagsPath(cfg);
    if (!fs.existsSync(f)) return {};
    return JSON.parse(fs.readFileSync(f, 'utf8'));
  } catch {
    return {};
  }
}

export function setFlag(cfg, id, patch) {
  const flags = loadFlags(cfg);
  const cur = flags[id] ?? {};
  flags[id] = { ...cur, ...patch, at: new Date().toISOString() };
  const f = flags[id];
  const hasTags = Array.isArray(f.tags) && f.tags.length > 0;
  if (!f.starred && !f.read && !f.note && !hasTags) delete flags[id];
  const file = flagsPath(cfg);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(flags, null, 1), 'utf8');
  return flags[id] ?? null;
}

// ───────────────────────────────────────── export & search

/** Minimal Markdown -> HTML (for export; escape first and substitute after, with no dangerous injection at all) */
export function markdownToHtml(md) {
  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const inline = (s) =>
    s
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>')
      .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g, '<a href="$2" target="_blank" rel="noreferrer">$1</a>');
  const lines = esc(md).split(/\r?\n/);
  const out = [];
  let inList = false;
  let inTable = false;
  const closeList = () => {
    if (inList) {
      out.push('</ul>');
      inList = false;
    }
  };
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (/^\|/.test(line) && /\|$/.test(line)) {
      const cells = line.split('|').slice(1, -1).map((c) => c.trim());
      if (cells.every((c) => /^:?-{2,}:?$/.test(c))) continue;
      if (!inTable) {
        closeList();
        out.push('<table>');
        inTable = true;
        out.push(`<tr>${cells.map((c) => `<th>${inline(c)}</th>`).join('')}</tr>`);
        continue;
      }
      out.push(`<tr>${cells.map((c) => `<td>${inline(c)}</td>`).join('')}</tr>`);
      continue;
    }
    if (inTable) {
      out.push('</table>');
      inTable = false;
    }
    const h = /^(#{1,6})\s+(.*)$/.exec(line);
    if (h) {
      closeList();
      out.push(`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`);
      continue;
    }
    if (/^\s*[-*]\s+/.test(line)) {
      if (!inList) {
        out.push('<ul>');
        inList = true;
      }
      out.push(`<li>${inline(line.replace(/^\s*[-*]\s+/, ''))}</li>`);
      continue;
    }
    if (/^\s*>\s?/.test(line)) {
      closeList();
      out.push(`<blockquote>${inline(line.replace(/^\s*>\s?/, ''))}</blockquote>`);
      continue;
    }
    if (/^(-{3,}|\*{3,})$/.test(line.trim())) {
      closeList();
      out.push('<hr/>');
      continue;
    }
    if (!line.trim()) {
      closeList();
      out.push('');
      continue;
    }
    closeList();
    out.push(`<p>${inline(line)}</p>`);
  }
  closeList();
  if (inTable) out.push('</table>');
  return out.join('\n');
}

export function exportReport(cfg, name, format = 'html') {
  // Export is always based on the markdown source, so switching the primary report file to any format
  // (html/adoc/json) does not affect export
  const md = markdownSource(cfg, name);
  if (md === null) return null;
  const base = path.basename(name).replace(/\.[^.]+$/, '');
  if (format === 'docx') {
    return {
      file: `${base}.docx`,
      mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      buffer: buildDocx({ title: base, markdown: md }),
    };
  }
  if (format === 'json') {
    return {
      file: `${base}.json`,
      mime: 'application/json; charset=utf-8',
      body: JSON.stringify({ name: path.basename(name), exportedAt: new Date().toISOString(), markdown: md }, null, 2),
    };
  }
  return { file: `${base}.html`, mime: 'text/html; charset=utf-8', body: htmlShell(base, md) };
}

/** Full-text search across reports */
export function searchReports(cfg, query, limit = 50) {
  const q = String(query ?? '').trim();
  if (!q) return [];
  const dir = resolveDir(cfg, 'reportsDir');
  if (!fs.existsSync(dir)) return [];
  const needle = q.toLowerCase();
  const hits = [];
  // no longer searches .md only: the .json source is covered too, so any output format stays findable
  for (const f of fs.readdirSync(dir).filter((x) => REPORT_EXTS.some((e) => x.endsWith(`.${e}`)))) {
    const text = fs.readFileSync(path.join(dir, f), 'utf8');
    const lines = text.split(/\r?\n/);
    const matches = [];
    lines.forEach((line, i) => {
      if (line.toLowerCase().includes(needle)) {
        matches.push({ line: i + 1, text: line.trim().slice(0, 240) });
      }
    });
    if (matches.length) hits.push({ name: f, count: matches.length, matches: matches.slice(0, 20) });
    if (hits.length >= limit) break;
  }
  return hits.sort((a, b) => b.count - a.count);
}

export { diffLines, diffStats, diffHunks };
