// reports.js — 报告与运行记录的存储 / report & run storage
import fs from 'node:fs';
import path from 'node:path';
import { resolveDir } from './config.js';

const DATE = () => new Date().toISOString().slice(0, 10);
const STAMP = () => new Date().toISOString().replace(/[:.]/g, '-');

export function ensureDirs(cfg) {
  for (const key of ['reportsDir', 'feedsDir', 'logsDir']) {
    fs.mkdirSync(resolveDir(cfg, key), { recursive: true });
  }
}

export function saveReport(cfg, { markdown, mode = 'daily', date = DATE() }) {
  const dir = resolveDir(cfg, 'reportsDir');
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${mode === 'merch' ? 'merch-' : ''}${date}.md`);
  const header = `<!-- generated by Vtuber's Monitor Link at ${new Date().toISOString()} -->\n\n`;
  if (fs.existsSync(file)) fs.appendFileSync(file, `\n\n---\n\n${header}${markdown}`, 'utf8');
  else fs.writeFileSync(file, header + markdown, 'utf8');
  return file;
}

export function saveFeedFiles(cfg, date, results) {
  const dir = path.join(resolveDir(cfg, 'feedsDir'), date);
  fs.mkdirSync(dir, { recursive: true });
  const index = [];
  for (const r of results) {
    if (!r.ok || !r.content) {
      index.push({ id: r.source.id, ok: false, error: r.error ?? r.note ?? null });
      continue;
    }
    const ext = r.ext ?? 'txt';
    const file = path.join(dir, `${r.source.id}.${ext}`);
    fs.writeFileSync(file, r.content, 'utf8');
    index.push({ id: r.source.id, ok: true, file: path.relative(resolveDir(cfg, 'feedsDir'), file), bytes: r.content.length });
    void file;
  }
  fs.writeFileSync(path.join(dir, '_index.json'), JSON.stringify(index, null, 2), 'utf8');
  return { dir, index };
}

export function listReports(cfg) {
  const dir = resolveDir(cfg, 'reportsDir');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const st = fs.statSync(path.join(dir, f));
      return { name: f, bytes: st.size, mtime: st.mtime.toISOString() };
    })
    .sort((a, b) => (a.name < b.name ? 1 : -1));
}

export function readReport(cfg, name) {
  const safe = path.basename(name);
  const file = path.join(resolveDir(cfg, 'reportsDir'), safe);
  if (!fs.existsSync(file)) return null;
  return fs.readFileSync(file, 'utf8');
}

export function runLogPath(cfg, label = 'run') {
  const dir = resolveDir(cfg, 'logsDir');
  fs.mkdirSync(dir, { recursive: true });
  return path.join(dir, `${label}-${STAMP()}.log`);
}
