// tools/verify-release.cjs - proofread a built release folder.
//
// ASCII only, CommonJS. Run it after tools/build-portable.cjs:
//
//   node tools/verify-release.cjs [--dir dist/VtuberMonitorLink]
//
// It checks the things that actually break a release:
//   1. required files exist and the exe runs its own --doctor
//   2. files that MUST be ASCII really are (launcher, quickstart, scripts)
//   3. every text file is valid UTF-8 (no mojibake, no BOM surprises)
//   4. no personal data leaked in (accounts, keys, absolute user paths)
//   5. no run data shipped (config.json with a key, reports/feeds/logs content)
//
// Exit code 0 = clean, 1 = problems found.

'use strict';

const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const EXE = process.platform === 'win32' ? '.exe' : '';

const TEXT_EXT = new Set([
  '.js', '.cjs', '.mjs', '.jsx', '.ts', '.json', '.md', '.txt', '.html',
  '.css', '.yml', '.yaml', '.sh', '.cmd', '.bat', '.ps1', '.map', '',
]);

// Files that must survive any system code page => ASCII only.
// App source is intentionally bilingual, so it is only checked for valid UTF-8.
const ASCII_MUST = ['README.txt', 'package.json'];

const SECRET_PATTERNS = [
  [/\bsk-[A-Za-z0-9]{16,}/, 'looks like an API key'],
  [/-----BEGIN [A-Z ]*PRIVATE KEY-----/, 'private key block'],
  [/[Aa]uthorization"?\s*:\s*"?[Bb]earer\s+[A-Za-z0-9._-]{20,}/, 'bearer token'],
  // A literal cookie value: a long run of cookie-safe characters straight after
  // the key. Deliberately excludes spaces/commas/quotes so ordinary source like
  // `cookie: r.cookieHeader, via: ...` is not mistaken for a leaked value.
  [/[Cc]ookie"?:?\s*[:=]\s*"?[A-Za-z0-9_%.\-]{40,}/, 'literal cookie value'],
  [/sessionid=[A-Za-z0-9%]{16,}/, 'session cookie'],
  [/\bSESSDATA=[A-Za-z0-9%*._-]{20,}/, 'bilibili session cookie value'],
  [/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/, 'email address'],
];

const PERSONAL_PATTERNS = [
  [/[A-Za-z]:\\Users\\[^\\"'\s]+/i, 'absolute Windows user path'],
  [/[A-Za-z]:\\~[^\\"'\s]*/, 'absolute workspace path'],
  [/\/(home|Users)\/[a-z0-9._-]+\//i, 'absolute POSIX home path'],
  [/\bDSH\b/, 'harness marker'],
  [/\bdsh-home\b/, 'harness marker'],
  // Generic: an absolute path on a non-standard drive is machine-specific.
  // Standard OS locations (Windows, Program Files, Users, temp) are allowed.
  //
  // The second lookahead is for **escape sequences**, and it is not cosmetic: a plain
  // `[A-Z]:\\<anything>` rule also matches the five characters `s:\n` + backslash inside a
  // template literal (e.g. a message that ends a line with `files:\n`), which aborted a whole
  // release over a string that contains no path at all (BUGS #67). `\n`, `\t`, `\u1234` … are
  // excluded, while a real directory called `node` or `temp2` still trips the rule. Known blind
  // spot, accepted on purpose: a one-letter directory named exactly `n` / `t` / `u` … is missed.
  [
    /[A-Z]:\\(?!(Windows|Program Files|ProgramData|Users|temp|Temp|System32)\b)(?!(?:n|t|r|b|f|v|0|u|x)(?![A-Za-z0-9_.-]{2,}))[^\\"'\s]{2,}/i,
    'hard-coded absolute drive path',
  ],
];

/**
 * Runtime state (**never shipped in the release package**, excluded by make-zip.mjs).
 * The build deliberately keeps it around; the secret scan and the "already published data" check both
 * have to tell them apart by this list.
 */
const RUNTIME_STATE_RELS = ['config.json', 'reports', 'feeds', 'logs', 'watch', 'thumbs', 'advice', 'vdb'];

/**
 * Find the release-package manifest generated by make-zip.mjs (next to the zip or one level above it).
 * Why a manifest: plain Node has no zip reader, yet "does the package really contain runtime data" must be
 * assertable - so let the packaging script write the file list itself and have the verifier read the JSON.
 */
function findZipManifest(dir) {
  const dirs = [dir, path.dirname(dir)];
  for (const d of dirs) {
    if (!fs.existsSync(d)) continue;
    const hit = fs
      .readdirSync(d)
      .filter((f) => f.endsWith('.zip.manifest.json'))
      .map((f) => path.join(d, f));
    if (hit.length) {
      hit.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);
      return hit[0];
    }
  }
  return null;
}

/**
 * On a secret hit, replace the secret itself and keep only "where, how long".
 * The first duty of a self-check is not to leak - writing the raw API key into stdout/logs means
 * manufacturing an incident of your own.
 */
function redact(line, re) {
  const flags = re.flags.includes('g') ? re.flags : re.flags + 'g';
  return line
    .replace(new RegExp(re.source, flags), (m) => m.slice(0, 3) + '\u2026<' + m.length + ' chars redacted>')
    .trim()
    .slice(0, 120);
}

// Private names must not be hard-coded here either: this file ships with the
// release. They come from $SANITIZE_NAMES or the gitignored .sanitize-names.
function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function loadPrivateNames() {
  const names = [];
  if (process.env.SANITIZE_NAMES) names.push(...process.env.SANITIZE_NAMES.split(','));
  try {
    const file = path.join(ROOT, '.sanitize-names');
    if (fs.existsSync(file)) names.push(...fs.readFileSync(file, 'utf8').split(/\r?\n/));
  } catch (e) {
    /* ignore */
  }
  return [...new Set(names.map((s) => String(s).trim()).filter((s) => s && s.indexOf('#') !== 0))];
}

const PRIVATE_NAMES = loadPrivateNames();
if (PRIVATE_NAMES.length) {
  PERSONAL_PATTERNS.push([
    new RegExp(PRIVATE_NAMES.map(escapeRe).join('|'), 'i'),
    'private name leftover (' + PRIVATE_NAMES.length + ' configured)',
  ]);
}

const EXAMPLE_HINT = /(<name>|<user>|<username>|example|placeholder|YOUR_|xxxx|\.\.\.)/i;

function parseArgs(argv) {
  const out = { dir: path.join(ROOT, 'dist', 'VtuberMonitorLink'), verbose: false };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--dir') out.dir = path.resolve(argv[++i]);
    else if (argv[i] === '--scan-only') out.scanOnly = true;
    else if (argv[i] === '--verbose') out.verbose = true;
  }
  return out;
}

function walk(dir, out, skip) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (e) {
    return out;
  }
    for (const e of entries) {
    const p = path.join(dir, e.name);
    const rel = path.relative(SKIP_ROOT, p).replace(/\\/g, '/');
    if (skip && skip(rel, e)) continue;
    if (e.isDirectory()) walk(p, out, skip);
    else {
      // A symlink (or a junction) is reported as a plain entry; resolve it so a
      // link to a directory is never handed to readFileSync.
      try {
        if (fs.statSync(p).isDirectory()) continue;
      } catch (err) {
        continue;
      }
      out.push(p);
    }
  }
  return out;
}

/** Decode strictly; returns null when the bytes are not valid UTF-8. */
function decodeUtf8(buf) {
  try {
    return new TextDecoder('utf-8', { fatal: true }).decode(buf);
  } catch (e) {
    return null;
  }
}

function isAscii(str) {
  for (let i = 0; i < str.length; i++) if (str.charCodeAt(i) > 127) return false;
  return true;
}

let SKIP_ROOT = ROOT;

function main() {
  const args = parseArgs(process.argv.slice(2));
  SKIP_ROOT = args.dir;
  const problems = [];
  const notes = [];

  if (!fs.existsSync(args.dir)) {
    process.stderr.write('release dir not found: ' + args.dir + '\n');
    process.exit(1);
  }

  const name = path.basename(args.dir);
  const exe = path.join(args.dir, name + EXE);
  process.stdout.write('\nproofreading: ' + args.dir + '\n\n');

  // ---------------------------------------------------------------- 1. layout
  //
  // --scan-only: do only the "text scan" (encoding / ASCII rules / secrets / personal paths) without
  // requiring the release directory layout. The external publishing script needs it to scan a **source
  // copy** - the source tree obviously has no exe and no app/server/node_modules, so all of those MISS
  // lines are false positives. Rather than filtering the output at the call site (which amounts to taping
  // the checker's mouth shut), give it a proper mode.
  if (!args.scanOnly) {
  const required = [
    [name + EXE, 'launcher executable'],
    ['package.json', 'version source'],
    ['README.txt', 'ASCII quickstart'],
    [path.join('app', 'server', 'src', 'index.js'), 'server entry'],
    [path.join('app', 'server', 'package.json'), 'server manifest'],
    [path.join('app', 'web', 'dist', 'index.html'), 'built web UI'],
    [path.join('app', 'server', 'node_modules'), 'production dependencies'],
  ];
  process.stdout.write('1. required files\n');
  for (const [rel, why] of required) {
    let ok = fs.existsSync(path.join(args.dir, rel));
    if (!ok && rel.endsWith('node_modules')) {
      // npm may hoist one level up; either location resolves for the server.
      ok = fs.existsSync(path.join(args.dir, 'app', 'node_modules'));
    }
    process.stdout.write('   ' + (ok ? '[ok]  ' : '[MISS]') + ' ' + rel + '  (' + why + ')\n');
    if (!ok) problems.push('missing ' + rel + ' (' + why + ')');
  }

  // --------------------------------------------------------------- 2. doctor
  process.stdout.write('\n2. exe self-check (--doctor)\n');
  if (fs.existsSync(exe)) {
    const r = spawnSync(exe, ['--doctor'], { encoding: 'utf8', cwd: args.dir, timeout: 60000 });
    const text = (r.stdout || '') + (r.stderr || '');
    for (const line of text.trim().split(/\r?\n/)) process.stdout.write('   | ' + line + '\n');
    if (r.status !== 0) problems.push('--doctor exited with ' + r.status);
    const v = spawnSync(exe, ['--version'], { encoding: 'utf8', cwd: args.dir, timeout: 30000 });
    const ver = (v.stdout || '').trim();
    process.stdout.write('   --version -> ' + ver + '\n');
    const pkgVer = JSON.parse(fs.readFileSync(path.join(args.dir, 'package.json'), 'utf8')).version;
    if (ver !== pkgVer) problems.push('exe version ' + JSON.stringify(ver) + ' != package.json ' + pkgVer);
  } else {
    problems.push('no executable to check');
  }
  } // <- /--scan-only skips sections 1 and 2

  // ------------------------------------------------------------ 3. file pass
  process.stdout.write('\n3. text files: encoding, ASCII rules, secrets, personal paths\n');
  const files = walk(args.dir, [], (rel, e) => {
    // Third-party code is neither ours to police nor worth the noise.
    if (rel.indexOf('node_modules/') !== -1) return true;
    if (rel.startsWith('pw-browsers/')) return true;
    // This machine's runtime state (config.json / history / logs) is not in the release zip - make-zip
    // guarantees that, and the manifest check (section 5) keeps an eye on it. So it is skipped here;
    // otherwise every self-check would treat "your own key inside your own dist" as a release incident
    // (false alarms make people ignore real ones).
    if (RUNTIME_STATE_RELS.some((r) => rel === 'app/' + r || rel.startsWith('app/' + r + '/'))) return true;
    return false;
  });

  let asciiFiles = 0;
  let utf8Files = 0;
  let binaryFiles = 0;
  const bomFiles = [];

  for (const abs of files) {
    const rel = path.relative(args.dir, abs).replace(/\\/g, '/');
    if (rel === name + EXE) continue;
    const ext = path.extname(abs).toLowerCase();
    const buf = fs.readFileSync(abs);

    if (!TEXT_EXT.has(ext)) {
      binaryFiles++;
      continue;
    }
    // A NUL byte in the first 4 KB means it is really a binary blob.
    if (buf.subarray(0, 4096).includes(0)) {
      binaryFiles++;
      continue;
    }

    const text = decodeUtf8(buf);
    if (text === null) {
      problems.push('not valid UTF-8: ' + rel);
      continue;
    }
    utf8Files++;

    if (buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf) bomFiles.push(rel);

    if (ASCII_MUST.includes(rel) && !isAscii(text)) {
      problems.push('must be ASCII-only but is not: ' + rel);
    }
    if (isAscii(text)) asciiFiles++;

    // Secrets / personal data, ignoring documentation examples.
    const lines = text.split(/\r?\n/);
    const secretPatterns = SECRET_PATTERNS.map(([re, why]) => [re, why, true]);
    const personalPatterns = PERSONAL_PATTERNS.map(([re, why]) => [re, why, false]);
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      for (const [re, why, isSecret] of secretPatterns.concat(personalPatterns)) {
        if (!re.test(line)) continue;
        if (EXAMPLE_HINT.test(line) && !/sk-[A-Za-z0-9]{16,}/.test(line)) continue;
        // On a secret hit report only "which file, which line, how long" and **never echo the secret
        // itself**: a self-check printing the raw API key into the console/log is a leak in itself
        // (it really happened).
        problems.push(rel + ':' + (i + 1) + '  ' + why + ' -> ' + (isSecret ? redact(line, re) : line.trim().slice(0, 120)));
      }
    }
  }

  process.stdout.write(
    '   scanned ' + (asciiFiles + utf8Files - asciiFiles) + ' text files, ' +
      asciiFiles + ' pure ASCII, ' + binaryFiles + ' skipped as binary\n'
  );
  if (bomFiles.length) notes.push('UTF-8 BOM present in: ' + bomFiles.join(', '));

  // ------------------------------------------------------------- 4. syntax
  // This one was taught by a real incident: an object key starting with a digit (the dictionary key for
  // "3D debut", and 2434) stopped the server from starting, while the packaging script only looked at the
  // exe's --doctor (which had not loaded that module yet). Every shipped JS goes through node --check, so
  // a syntax error never goes out on the road again.
  process.stdout.write('\n4. shipped script syntax (node --check)\n');
  const scripts = walk(args.dir, [], (rel) => rel.includes('node_modules/') || rel === name + EXE).filter((p) =>
    /\.(js|cjs|mjs)$/i.test(p)
  );
  let syntaxBad = 0;
  for (const p of scripts) {
    const r = spawnSync(process.execPath, ['--check', p], { encoding: 'utf8', timeout: 30000 });
    if (r.status !== 0) {
      syntaxBad++;
      const first = String(r.stderr ?? '').trim().split(/\r?\n/).slice(0, 3).join(' | ');
      problems.push('syntax error in ' + path.relative(args.dir, p).replace(/\\/g, '/') + ' — ' + first);
    }
  }
  process.stdout.write('   checked ' + scripts.length + ' scripts, ' + syntaxBad + ' with errors\n');

  // ------------------------------------------------------------- 5. run data
  //
  // Note the division of labour here: `dist/<name>/app/` is **the developer's own local runtime data**
  // (API keys, historical reports). The build now deliberately keeps it (otherwise every re-pack empties
  // the key, which was really run into). What actually decides "what goes out to the public" is the zip,
  // asserted by make-zip.mjs's manifest (.manifest.json) - so dist/app is only a note here, no longer a
  // problem.
  process.stdout.write('\n5. shipped run data\n');
  const RUNTIME_RELS = RUNTIME_STATE_RELS;

  const manifestPath = findZipManifest(args.dir);
  if (manifestPath) {
    const rel = path.relative(args.dir, manifestPath).replace(/\\/g, '/');
    try {
      const man = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
      const bad = (man.files ?? []).filter((f) => RUNTIME_RELS.some((r) => f === 'app/' + r || f.startsWith('app/' + r + '/')));
      if (bad.length) {
        problems.push('release zip includes runtime state: ' + bad.slice(0, 5).join(', ') + (bad.length > 5 ? ` (+${bad.length - 5})` : ''));
      } else {
        process.stdout.write(
          '   [ok]   release zip is clean (' + (man.files ?? []).length + ' files, ' + (man.excluded ?? []).length + ' runtime paths excluded)  -- ' + rel + '\n',
        );
      }
    } catch (e) {
      problems.push('zip manifest is not valid JSON: ' + rel);
    }
  } else {
    notes.push('no zip manifest found next to the build; build with npm run build:portable to get one');
  }

  const cfgPath = path.join(args.dir, 'app', 'config.json');
  if (fs.existsSync(cfgPath)) {
    try {
      const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
      // Find apiKey recursively: it used to be llm.apiKey and is now llm.providers[].apiKey - looking at
      // the old path alone yields a "no key" false negative (run into before).
      const hasKey = (function find(v) {
        if (!v || typeof v !== 'object') return false;
        for (const [k, val] of Object.entries(v)) {
          if (/^api_?key$/i.test(k) && typeof val === 'string' && val.trim()) return true;
          if (find(val)) return true;
        }
        return false;
      })(cfg);
      // report only whether a key exists, never print the key itself
      notes.push('app/config.json = your local settings (' + (hasKey ? 'an API key is stored here' : 'no API key stored') + '); make-zip keeps it out of the release zip');
    } catch (e) {
      problems.push('app/config.json is not valid JSON');
    }
  } else {
    process.stdout.write('   [ok]   no app/config.json (created on first save)\n');
  }
  for (const d of ['reports', 'feeds', 'logs', 'watch', 'thumbs', 'advice', 'vdb']) {
    const dir = path.join(args.dir, 'app', d);
    const count = fs.existsSync(dir) ? walk(dir, []).length : 0;
    if (count) notes.push('app/' + d + '/ holds ' + count + ' file(s) of local run data (kept out of the release zip)');
    else process.stdout.write('   [ok]   app/' + d + '/ is empty or absent\n');
  }

  // ---------------------------------------------------------------- 5. report
  process.stdout.write('\n6. result\n');
  for (const n of notes) process.stdout.write('   note: ' + n + '\n');
  if (problems.length) {
    for (const p of problems) process.stdout.write('   PROBLEM: ' + p + '\n');
    process.stdout.write('\n' + problems.length + ' problem(s) found.\n\n');
    process.exit(1);
  }
  process.stdout.write('   clean - no problems found.\n\n');
  process.exit(0);
}

main();
